<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_OrderInTransit</name>
   <tag></tag>
   <elementGuidId>beafbbb7-ea33-4dd4-94f9-458ff2776653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='InventoryTransfer']/table/tbody/tr[1]/td[5]</value>
   </webElementProperties>
</WebElementEntity>
