<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_SerialNumberToReceive</name>
   <tag></tag>
   <elementGuidId>d6a6cfe9-cd22-428a-9f4e-a99fe08a578a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='InventoryTransferItems']/table/tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
