<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Approve</name>
   <tag></tag>
   <elementGuidId>5ab3e535-e6c3-485e-ad06-8a11c95f62d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='BlockedAccounts']/table/tbody/tr[td[normalize-space()='${customerAccount}']]/td/a[contains(.,'Approve')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='BlockedAccounts']/table/tbody/tr[td[normalize-space()='${customerAccount}']]/td/a[contains(.,'Approve')]</value>
   </webElementProperties>
</WebElementEntity>
