<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Products</name>
   <tag></tag>
   <elementGuidId>2e9bfafc-eb29-4c01-bc38-ce49b32ebec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DealersOutletList']/table/tbody/tr[td[text()='${outletCode}']]/td/a[text()='Products']</value>
   </webElementProperties>
</WebElementEntity>
