<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Check and mark stock ready for sale</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-19T11:00:42</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d7252266-9183-45a1-8af2-88cf7ba0f36c</testSuiteGuid>
   <testCaseLink>
      <guid>c443e62d-3c3a-4bc5-87a3-7c23eee4125f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Check Stock/Steps_check stock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aa5ebc5-c068-4142-9d0e-c62f43ced3e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d17e22-4b40-420a-9f51-3faaee2fecdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abdd946c-c42d-4f23-ab19-f25cc62b9418</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b27f1914-ff6d-44ff-bfb5-52be8ba69349</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eaec00c9-3246-43b8-821b-4e180369337b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Mark Stock For Sale/steps_markstockfor sale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a5718fd-b020-4e20-b6f7-03ff4c33de20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47e027ff-cad4-4e0a-b373-724991a2570b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dce6cfd2-fd5f-43cb-8240-82ebe76e0633</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c43a654-436a-4f48-88ee-b694dcf3c398</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
