<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Dispatch order</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c1d8a0b8-3e06-4159-ac5a-dbd45ff0a2b8</testSuiteGuid>
   <testCaseLink>
      <guid>2dbb2f8b-29d9-418a-8c59-86cba3a3f015</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Service Order/Steps_Service Order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>043ba446-9bae-4215-8c47-71c69f9b2aad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b860a8a-4689-43c9-9bb7-44d586c26a50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d0aa5a0-696e-45a4-9f27-0301f2796444</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5df04f24-9ed6-44a0-922b-0dd4e00e5d24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6f5cf3e-d0fc-4b81-81f5-d3c16aaf862d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Dispatch Order/Dispatch Checked order</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>862e8774-ca9a-4eb0-9e2b-bceca5503a23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3408a306-5588-4ff5-b392-fa031c72b9c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
