<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Item Types</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8d185166-f56c-43ee-bf67-cd70601de995</testSuiteGuid>
   <testCaseLink>
      <guid>d194830c-2957-4c75-ad91-1ef2a677c9b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Item Types/steps_Item Types</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>970a3866-5d78-44b4-b9a8-3135c569cfd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Item Types/List metered items types</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2ebac574-bd32-407c-9d9b-e7f38ee45220</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Item Types/validate_blank fields(Add item types)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc75c4ed-6f39-4c61-b3cc-bf387f8bf3a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c790226-496a-4672-9d2e-d764c890cb1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27eb959e-10ff-4c2e-8943-3c5eb702829b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a85b7a05-a8ee-4870-8f7e-6319d3d6fe75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e90f4d94-d297-45d5-96e7-b2d4ff8d8de8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Item Types/verify_Add Metered Item Type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b9658d-5eda-4337-a3e2-6872701488b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef3e011-353d-4168-a2c7-9f375402b0b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50bb76cb-7b42-4ac9-ba0a-d5d532644fbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0650e121-fa18-40d2-889c-ca8c98ebeb7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bd0ebfd-62e8-411a-940c-c2cd59a8a2ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68fea8e0-908a-4791-a09f-caee4cd621a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f54d7cbd-97a5-426b-9330-2e7ced502353</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>362c9cbe-897d-46e2-9008-a73a6051c993</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Item Types/verify_Add Kingfisher metered item type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59f17add-70ec-40d1-b8fd-31cfd2c00efa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74305faf-aa90-41ac-b29b-ef1b3be405bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef54e09f-2111-40c0-bdab-6aa4cd8290fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dbdacc0-9bf1-44d0-b642-e21147d83bc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cfd8378-6ab4-4f90-8a09-4435e7de8ea8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>893083df-ec5b-4530-b839-6bf2b47dcfea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Item Types/verify_Add bundled item type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad77ea90-faf6-4c95-a5a8-f5a0d813cd76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0f71fd0-ef29-4f9b-822e-0618ec4abf1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c04c75bd-1e29-4f27-b129-611a856b67c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ab08e22-7219-4c5f-b309-69f43c2efe14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07f64f6d-2463-4b75-81d4-46372517743b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3273051-83b1-466a-afb2-c0ae9722629a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
