<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Manifest Upload Test Cases</description>
   <name>Manifest Upload</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>95f8f714-f8a9-4a15-b1b2-dc8f59590ac4</testSuiteGuid>
   <testCaseLink>
      <guid>f1a9ddec-21af-46cb-b650-070296f8b72e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Uploading metered Item Manifest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4487e167-1b1a-4595-9663-8a3d37b7ef52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b07fcc-6e1a-4519-a7c2-bbb43da8b2fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde994af-3f3d-49f6-80d8-b5da681ae173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ac3c015-5b94-4d82-9ac6-07b9a1670dcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7941fd5-3852-4df8-8b05-733aa5351c53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fecada69-5f9b-46d7-a22a-6260c63a9de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a4b878-9c74-4303-be4a-231453302b18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3a03ae6-101c-4f40-bff0-02c5664663d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d85c58b-ac96-4604-8a6b-029d648925d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a91714d2-8c4f-4e64-880a-1762e4a24a27</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d92c871-d7fd-4f94-b33d-b8a89bf64d7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Uploading Kingfisher Item Manifest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c270069-d9bf-449b-9bdb-fc17602df126</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8f9ef3e-55d7-468f-9fb9-45235c5201e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fd17f2a-e84c-4d8b-86dc-32c053359646</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b3901b-9bbf-4cd4-8d1d-bb618db5e1ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fceadc92-5b9e-4116-8000-20f5a05a3d63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0903e21e-b1dc-4219-92fb-05778518a4d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d994605-7927-448f-87a0-3791547537ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d1c873e-05ef-4eff-b045-fbd999a39581</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9cf353-e27e-4550-a799-67a7594c3984</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86e763a8-730c-48f0-b2a7-8306631d27b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Uploading Hammerkop Manifest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7eb48130-a450-4873-8372-8db7edfae04c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>244104dd-93bd-4e9c-a6b1-62adf2dff9ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>913d7346-5eda-49fb-81af-1134507e83a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d002bb6e-0d92-4e61-87e7-b589ef831905</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1aec4318-be48-4a04-ad06-2e616f5d371b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Metered Uploaded Items Lists</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16cc982c-d96d-4324-8f29-bb8eb8691c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfe1dccc-3757-4240-89c4-db78c895a1f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73efbbc3-f600-45a4-86b2-bee89d656b9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12bbcfc9-b23a-4c86-88a3-79530132d08b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1abcf00c-d735-48ce-a812-b4fcc19723a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88719649-d52a-495e-9e43-f0045754c839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d127f10c-93eb-4314-b26e-7585a7a7ff08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5264e304-9e49-4bd6-999b-754ce0724afb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
