<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Repair pool Transfers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-19T12:33:30</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0e0d919e-4c51-46fd-8775-08233632d362</testSuiteGuid>
   <testCaseLink>
      <guid>95d18768-cd3c-4362-ac4c-27ae1358df86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool Transfers/verify_Repair Pool Transfers Out</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f78c998-731f-4090-b10f-b65368da0296</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddbfb64d-7d24-4c7e-9a4a-2c654b786dd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3ce3c04-c215-4ebe-beb5-89d990f9ec4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112bf9ea-f377-46c6-83b2-31705d41219c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8547c393-065d-4bd2-9d79-a227985ef124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1c4910b-d26c-4f9c-a2f9-b0883fd77101</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16bf310d-3a7a-47ce-b81f-c38cb754e897</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool Transfers/verify_Repair Pool Transfers In</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee1c82a-d3b2-4f00-95b0-f46ea4e1669d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17150d63-b3d7-4378-9b16-a39b6d66c35b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>453be2a4-71c9-4efb-bb1c-17b7bf99b370</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
