<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Repair Pool</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d1763f81-8e07-48be-9377-d0478dc28d12</testSuiteGuid>
   <testCaseLink>
      <guid>4bd08677-f630-4999-9919-c1976649741e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_Repair process</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b38bfd68-f25c-4ee7-b8cf-07cead7a8020</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d20dfa9-8741-445c-a036-2903d1c47524</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f302fdcf-24a7-4fb6-bf7f-8f4e76c84114</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>685454ce-b785-49b7-9840-c52b3cf0f8c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Repair Process</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>182d19f3-5c5f-42a2-883c-42d6b3aa7e5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d579f3-7fc3-4d7b-8860-e479385888b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f4fe6ab-9187-4737-a5ba-8240e06c5ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>884522ab-9edf-40e2-8a00-5ed3e8156f7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5031cf1-43cd-45ee-a843-211f0a3a261a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb7907d8-258e-4f2d-a0e1-699f3945f52a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ffe2bbe-6b9b-4f54-9615-c0bc72a71901</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_blank fields for repair returned device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb8a786-1fc0-4c2f-ba34-317f5f0424e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae8ca94b-2ca6-4c5c-9748-014446e5f131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a333905-aab4-424f-9508-dd6d0b44fb26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a447fd32-e61a-4bac-af1e-3ed23ad2a592</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eba9a7ed-0049-4617-86ef-5817df6e59ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08770d38-d413-4df0-873c-8dbf7a47edac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_resolution field is required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34aa644f-39aa-4696-883f-01e59c04d43b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f81baf7e-4014-4c44-9c00-a6bab61f1fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fab0719a-0b64-4ea7-8c89-aa85206eb992</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48840b79-566c-4312-b4c0-631d5ad6a734</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Repair returned devices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92861f34-f8ac-4b2d-837b-bd5d75e65b2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a041bf62-ba62-497f-8d57-0dd9f28a8181</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d521269-fe53-4dd8-af84-488823505190</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbfef6f7-e259-4c48-9b69-348e2e0d1725</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ccd3fe-ccf0-4c4e-b386-87ac95271b96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4c21eff-d579-4b97-a794-380641aab57c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_blank fields for approve device repair</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5b44311-0644-459a-90c3-19a92d831eac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1912430-5a35-451d-aae0-214f583bffa5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61b2458d-ee4b-49e8-afee-44a0b4218ffb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a49eb633-8315-4909-99de-efdeb0d3284a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_Approval status is a required field</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>857bc567-9863-44bc-860f-29aa05d354ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c669759b-4890-4b2e-8c52-963123c9a09b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8352d76f-f278-46e4-b7f8-e64eac41731c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Approve device repair</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb67a162-75c7-4f53-8411-597641352122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc182a92-a511-4c42-9787-2354e139150a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e77f96-98f5-46b7-8036-146cb6d9f1fb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
