<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes all the operations done on M-kopa III device</description>
   <name>M-kopa III</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8717ef8e-4935-4302-8bbd-7c6b2ab22e22</testSuiteGuid>
   <testCaseLink>
      <guid>4beb0004-a664-46c6-87e5-1a17ef2788af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA III 2763/Send Credits/Steps send credit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86dcf391-6f78-44df-bdce-a5c50c3a86f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6117bd6-dd25-4904-bc46-d69e703f70e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c7b728b-73ca-4bb6-a01f-d7d2ab9e457a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c85983eb-9b78-4b47-a91c-14e289b18817</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2aaad9b-cecd-4c84-8954-b0630bdad9d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fed60c76-d2a5-48d4-b2ca-f4bc2777063d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA III 2763/Send Credits/verify_View Credits Sent History M-KOPA III</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4c005a8-8505-49e7-91fe-650840f075bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f909bd86-6565-4bb0-bf04-63b32fff9232</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f76c3bf7-f4c2-45bf-9cfb-a2b1f9d96bd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47171a78-b6fb-46f0-98d4-a2cc7d05e9b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b16a040-4cc0-4568-ba73-e89e1cd9f13d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4828a5ec-b7d7-4a6e-bf88-7186f52cf6c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7172fd3d-66fe-4e8c-a795-634fb4163bc2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8dc1d66-3bef-43bd-b7a0-b35d027ca32d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA III 2763/Send States/Steps_Send States MKOPA III</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abc0859f-f112-48ff-bb1b-aaafb6683c13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f4709f-e3ee-4586-8aa4-aef623ec8b13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e89d5d60-7c04-42e2-8cb1-fd74fef9e5e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e655795a-c2c8-4c93-a111-c5ff27d5048f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>decd86ec-60f9-4be8-a4af-f7b55625183d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12513635-e755-488a-80f0-4927994bf9d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba14586-0c76-4f6e-92be-c9a63611de20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96c1d222-8fa5-4fce-af06-6891efa7f3f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd1aece0-a3fd-419a-9bd4-d962288b6672</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA III 2763/Send States/verify_View states sent History MKOPA III</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eabbfe0f-6dcc-4c72-903c-c85d1981d28f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ecabc8-92a1-432c-b1b2-cebd46af4558</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfde8c6b-9a5c-474c-8495-b9bbef396842</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9db39f75-decf-4f71-892a-fb2f0ff98756</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ff39fe2-7302-454e-bc9d-fee7d9cf1c0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a56bdeb-59f5-4f50-9222-f59cda68c297</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36164167-8130-4d3c-be3c-d4fe94ea51d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df34c153-cb99-42b4-a571-cfa8dbd944f4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
