<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Loan Payment Plan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>14eb7a09-3bc5-43c0-8583-9cf225584347</testSuiteGuid>
   <testCaseLink>
      <guid>60afc45f-a417-42e2-af9f-c7817e1aec59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Products/Payment Plans/Loan Payment Plan/verify_ValidLoanType</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1a6a5a7-7af7-43f8-b27e-cbd807f67b50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8bc49b2-84d4-4bfe-b5f9-2e1af6df343a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b42af394-2d3b-466f-a0ab-f14a766893a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4da89f6-9ad1-4816-bb20-70d3cafc2bc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e56917d6-8de7-44bc-92d4-de5bb087d6d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aabaccdb-4319-44ce-9c92-cb699caac80c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b748ae2-03bb-4dcb-9f3d-c1f7d57e1d08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>037b814f-0b7f-4eef-ad3d-4ac3efb39e01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f35676af-59b6-40c5-ad9a-6683539612e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae286c14-d3c0-44a4-ae8e-56548c934621</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe7015b-30f2-4fb5-8485-7db6b19aaae0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>933b6e49-e213-4280-b45a-4bdb78b3f383</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Products/Payment Plans/Loan Payment Plan/verify_Loan Payment Plan Added</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8ca7e96-8405-4221-8a7a-2b1af0290992</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d089558-2a1c-474a-911c-616f7066ca54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849782cb-1d0d-4d2e-8093-1537194de552</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>743f8648-e56a-41ad-805f-764b15c096ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbe2368-69b4-4b0e-b0e6-2fd06d3dfbfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a48d9626-c044-4504-9fa5-655e6764823f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3a0af6b-5787-45ed-b44a-4a8d4d5fdd51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68b75278-5f7d-4b15-a2bf-5866de880fd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>012249d4-7022-4d44-b9c5-8daf415696b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0766ea4-d4b3-4b84-8dbf-b734f49ce192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>876d833a-0672-4b5e-bcbc-0dc4ae694fcf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8240b657-f1be-4a64-99ff-f21acda29b12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Products/Payment Plans/Loan Payment Plan/verify_LoanPaymentPlansApproval</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>531d93f3-1823-4bd9-af76-7e0664f1bfe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1251a0c-2b6c-4ab7-8026-3a32ae1f0324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc37f890-7a48-4655-b0bb-5ae809fffce3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
