<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_packaging</name>
   <tag></tag>
   <elementGuidId>d4c47d53-97eb-40ca-8b2b-c09a6751f6b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//ul/li[text()='${packaging}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//ul/li[text()='${packaging}']</value>
   </webElementProperties>
</WebElementEntity>
