<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Repair Pool</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>860ce6ef-deab-4c8b-b323-de83deda2b2a</testSuiteGuid>
   <testCaseLink>
      <guid>c67eaf69-c20e-4faf-a645-452d4e42b45a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_blank fields for repair returned device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb8a786-1fc0-4c2f-ba34-317f5f0424e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae8ca94b-2ca6-4c5c-9748-014446e5f131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a333905-aab4-424f-9508-dd6d0b44fb26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a447fd32-e61a-4bac-af1e-3ed23ad2a592</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eba9a7ed-0049-4617-86ef-5817df6e59ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74c9d497-0612-4f87-a987-460f1c6bb283</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_resolution field is required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34aa644f-39aa-4696-883f-01e59c04d43b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f81baf7e-4014-4c44-9c00-a6bab61f1fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fab0719a-0b64-4ea7-8c89-aa85206eb992</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59ccfa62-d197-468a-b02b-0bec4f1e6724</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Repair returned devices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92861f34-f8ac-4b2d-837b-bd5d75e65b2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a041bf62-ba62-497f-8d57-0dd9f28a8181</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d521269-fe53-4dd8-af84-488823505190</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbfef6f7-e259-4c48-9b69-348e2e0d1725</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ccd3fe-ccf0-4c4e-b386-87ac95271b96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db6611eb-6034-42b8-be53-c22de706f47c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_Approval status is a required field</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>857bc567-9863-44bc-860f-29aa05d354ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c669759b-4890-4b2e-8c52-963123c9a09b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e027939-2c9c-4301-98c2-47fa0859bbca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Approve device repair</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb67a162-75c7-4f53-8411-597641352122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc182a92-a511-4c42-9787-2354e139150a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e77f96-98f5-46b7-8036-146cb6d9f1fb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
