<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>executes all the requests made by dealers</description>
   <name>Dealer Requests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3df83f67-eb8e-46a1-a4b7-9a684c08dda3</testSuiteGuid>
   <testCaseLink>
      <guid>1be20cf3-c478-4991-ad11-55482e76dd4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Make Purchase Request/validate_required fields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab32d066-01a3-4677-8b75-7e1160b53029</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f896faa0-09f3-423d-8c6e-202a1ba8db3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1867e395-3b7a-4380-b082-ee1a0aebc78d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acfd8c52-9556-46a4-9d82-e0724c5934c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3df8c4c1-197b-4d2c-94e5-69ed843a7799</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8eca9e6-f377-4ef2-b80a-9805137e925d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81e3cd53-ad04-40c0-b51c-c3e1e6329ec9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Make Purchase Request/Steps_Make purchase Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b56089cb-dbe2-4b30-816c-5d888d8563ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2cee84-5447-4cb3-b909-27bb86744d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8e2e542-e8ef-497f-b52f-10b07dcab77c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44d99ff8-c236-4eda-ab56-887b24f2bd3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0222f677-5cd4-4e96-b1a2-4ea1d527af5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d0d3722-a998-4f13-a9d0-bcca33f28425</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Make Purchase Request/verify_Make Purchase Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c48564d-6887-41a4-b434-426d7396f58b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e787e5a-6b73-483c-8974-d13bd54537ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>825ad429-55f7-4ce5-9cec-b7b0b45a43bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295c4d3f-459f-40c4-a793-9e47b4300233</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6843a631-80f3-49bd-95b0-03a14220fc33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>192e8a5a-f437-41ac-ba4f-976b47ce311e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Approve Purchase Requests/Steps_approve purchase requests</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36f3c818-fc6a-4780-9d8b-0b6885f1cd51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d75416b7-fd13-4c6e-bb2c-d798ee91c582</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Approve Purchase Requests/verify_Purchase Request Approval</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9229e606-9fa1-4294-aff5-518b7432f10f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b33d8e4-6a10-4085-8f7d-a85756c914f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Order Administration/validate_order declined</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f069ee3a-97a5-4f38-b19f-4a5f7fb5672d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e844114-7e2a-4711-96c4-535c1cc9d86e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Order Administration/verify_Order declined</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f069ee3a-97a5-4f38-b19f-4a5f7fb5672d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18a8fa3b-02dd-4842-bb84-46acfe9b5b91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Order Administration/validate_Order Allocated Successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0710cf7d-4d9d-4573-9c8c-0a256d553eea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d19b156c-e106-463d-afcb-133fd31f41b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a72c7cb8-c90a-4c94-8aa5-ead17b252c3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Cancel Approved Dealer Order/verify_An Approved order is canceled</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac054794-605f-4325-a07a-e97803b9d2f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed91b87a-030f-4872-b2d6-15372ce0ed64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8d572ba-51a3-4721-bf09-5514ea76e935</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Return Stock Request/Steps to Place Return Stock Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5d36247-9a20-458b-b81d-82d472e3b5c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>921e8365-b968-40b9-ac59-8876d49872b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87310c46-6317-44cb-b702-8eb323487637</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b3ff22-c89b-4bf1-b736-0213dbf7f3cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f766722-88e6-4d53-b68c-6f7b6668e08f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1085dec-610c-434c-8272-492f7373c491</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e46a812-6837-44ed-a636-6f4c1076e079</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b238d4d6-da95-41cb-a3ef-8bd85cbdbf53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Return Stock Request/Steps_approve Return Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a8ba859-c178-4ac6-b9d0-b925a8f3a1a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74473a8f-aa26-4089-9649-c9f22e371c82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Return Stock Request/verify_Return Stock Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa8b2e8f-e400-4b90-baa9-997359d69823</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81713693-512d-423e-81cb-17804058f52c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd0ca290-f2b4-47e1-920e-dd45f64b811e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fe0a56a-cc45-4e18-af8f-14bd530307d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c0958e-7c02-4d14-88c9-0788cc563d85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2e3b7f1-f117-4907-ae69-68e620f9e2b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a11f912-edf7-4e0a-98f2-700b1fa06c54</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
