<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Dealer</name>
   <tag></tag>
   <elementGuidId>e5331998-ed1b-4c32-9d44-9fdb19358257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/table/tbody/tr[td[text()='Dealer:']]/td/div/div/span/span</value>
   </webElementProperties>
</WebElementEntity>
