<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SalesRep</name>
   <tag></tag>
   <elementGuidId>2292997a-dbad-424f-ab71-51994cb790dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div/ul/li[contains(normalize-space(),'${SalesRep}')]</value>
   </webElementProperties>
</WebElementEntity>
