<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Dealer</name>
   <tag></tag>
   <elementGuidId>c6c7820a-9ac8-4469-947c-12057c71846b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div/ul/li[contains(normalize-space(),'${DealerName}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div/ul/li[contains(normalize-space(),'${DealerName}')]</value>
   </webElementProperties>
</WebElementEntity>
