<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EntityType</name>
   <tag></tag>
   <elementGuidId>ff592fd2-12cc-488d-b12e-052d5576644a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div/div/ul/li[text()='${EntityType}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div/div/ul/li[text()='${EntityType}']</value>
   </webElementProperties>
</WebElementEntity>
