<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_returnOutlet</name>
   <tag></tag>
   <elementGuidId>af49297e-7602-4ed2-867a-54e8af36a3f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id=&quot;divBodyForm&quot;]/div/div[2]/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
