<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Operator</name>
   <tag></tag>
   <elementGuidId>d64b69af-6e80-4412-bd84-c973533ccd13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[16]/div/ul/li[contains(normalize-space(),'')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]/div/ul/li[contains(normalize-space(),'${return_Operator}')]</value>
   </webElementProperties>
</WebElementEntity>
