<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_incentives</name>
   <tag></tag>
   <elementGuidId>8738611f-b6e8-4b69-b9e0-6a4db6121e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='div-account-info']/div[1]/div/div[8]/div[2]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
