<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_AddOn</name>
   <tag></tag>
   <elementGuidId>ebb9166b-b5ff-455e-b8b8-21ef5511e833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='panelbar']/li[contains(normalize-space(),'${addOnName}')]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='panelbar']/li[contains(normalize-space(),'${addOnName}')]/a</value>
   </webElementProperties>
</WebElementEntity>
