<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_OutletProductTypeApproval</name>
   <tag></tag>
   <elementGuidId>207c3376-6fa8-458b-a591-b5e2c6dd36ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*//tr[td[text()='${producttype}']]/td/a[text()='Approve']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*//tr[td[text()='${producttype}']]/td/a[text()='Approve']</value>
   </webElementProperties>
</WebElementEntity>
