<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Area</name>
   <tag></tag>
   <elementGuidId>b29d9415-79eb-4074-bf2b-d2fc07980957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*/ul/li[text()='${selectArea}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*/ul/li[text()='${selectArea}']</value>
   </webElementProperties>
</WebElementEntity>
