<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Credit purchase upload</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-09T12:47:45</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1c232f92-6773-49f9-931c-caeb09e224f1</testSuiteGuid>
   <testCaseLink>
      <guid>fcded708-8ef2-49fc-9ac4-e9fd3cde5a13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Credit Purchase Payment Upload/verify_Credit purchase</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc54a1ab-a623-4f2d-b3dc-bb813910aa4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d66a77e3-2528-4524-92bf-ba140412bd63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>665b4789-e2f6-41c4-a27e-8021b7502426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c824fc8e-d1a4-429e-85d0-b26216d62b07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4559e515-f35e-4ba4-a997-0d615053ab34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b577dd30-366b-4467-80d7-d25b976adbc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69690d49-7fa5-4ecf-b098-1be8090fca8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a56d731-93a4-4cc4-8a16-40aadaea5525</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Credit Purchase Payment Upload/verify_credit sent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f76f6b61-b2f0-45da-8d2c-2051e69aa27d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dea66849-b0eb-432e-907e-07e1d20307ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd792c1d-4acb-4b18-aea0-9169afdbb4c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>479b9144-5ab6-40b1-bf0b-3d4d937b56fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae36c514-e3ef-4ef2-a496-0411b2810705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7da6a1c-8ef4-4891-b578-f6e19593c716</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
