<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Early completion discounts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-09T14:17:54</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e72040b1-fc27-4a44-a952-136331641b47</testSuiteGuid>
   <testCaseLink>
      <guid>c1be29fd-f078-448b-8e26-dc0286782520</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Early completion discount/verify_Early completion discount</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e5cc49d-0257-4a45-809f-e82f78c9838b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e27d3665-3bc1-441e-a83c-39c07802ad48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecda38a4-c195-45c3-a3c2-dbce06e67235</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d0df3d9-a75f-4498-8efc-0a2d5d9d9ca7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c03b25e-b948-44e3-8b51-fa1b5e9cfa5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7927c52b-2d18-4f54-88b8-9bf4de264d13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>346ffbc3-a7bb-4755-8162-a9d5f428f711</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a51342a-e9f6-4dcf-9d0a-bbb306d0de49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00261aa4-a294-48cd-80d3-db147a9e4c71</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
