<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_SerialNumberToReceive</name>
   <tag></tag>
   <elementGuidId>b4b459d6-830f-4867-a163-07d46be05166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='RepairPoolTransferItems']/table/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='RepairPoolTransferItems']/table/tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
