<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_StatusIsReceived</name>
   <tag></tag>
   <elementGuidId>23f6223d-96b2-4799-ae3f-ed072894d444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='RepairPoolTransfer']/table/tbody/tr[1]/td[text()='Received']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='RepairPoolTransfer']/table/tbody/tr[1]/td[text()='Received']</value>
   </webElementProperties>
</WebElementEntity>
