<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>manifest Upload</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-23T10:34:32</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d3f9935e-77f2-4eea-bfa2-3aac1003031f</testSuiteGuid>
   <testCaseLink>
      <guid>95a096b7-e368-426c-b0d9-ee2ef9f41e28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Data Duplicates in the Database</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86882527-4bd9-41ed-a745-11839f4732ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb59f05d-3646-4a3c-bdfd-3759699dd0cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5a6dad6-be48-4522-b8d8-a38138596a38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fee24d8b-61bf-40df-82f0-635dddd037a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c519eef-262d-4a6e-a15f-db43c7995411</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96d8ba1c-4d07-4500-bc7c-c5cb1fc9abe9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73fcb0f3-0491-4e54-85cd-7702322c7f6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Shipping Date Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c328ac-8348-47b3-bb75-fbfe6143a60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03bed94b-834f-4a14-8dd5-e3696382aa3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67999170-f7c0-42f5-a4ba-f50dfc368a1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18779ded-09d0-4ec6-a4f1-6032c9abd08a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>300b01fe-2f05-4b8b-945f-9c9bc6779fee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>653db032-af61-4586-a61a-c85428a845f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc436fc0-0d30-4b3c-9ac6-a250e210e0b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Duplicate Consignment No</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>409a6bf5-9ca6-4faf-a2e9-9a10320b6fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c6adb4-2f01-47c6-8bce-eca5f9c390e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d6a5880-2f2f-48f0-bebe-4f6ddf192fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ea8e21-70d5-4339-b2e4-95aea63234ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30f23dd3-fe6c-4780-8429-ba27a0374635</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9084848-e228-46db-a186-64d0a9057865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a590315-ec35-4658-906f-61b423cec05d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61079192-9703-4a3b-8214-a5ca84c998e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_csv File Extension Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec7676a-5f9f-44e0-ac04-7dcf8ce21e5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66a1a719-1bd6-4eeb-955d-a805a86db58c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>009f6356-dafe-4bf6-9912-f0c0655bbe6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a7595eb-d966-47a9-afe4-94f82e38f9df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d65c64-3bfc-4425-9beb-c7dcadba0d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f805360c-5f02-4f81-92bb-5068e7c4f184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a50d77a-6d56-4a69-89e0-c49efdaa106b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Uploading metered Item Manifest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4487e167-1b1a-4595-9663-8a3d37b7ef52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b07fcc-6e1a-4519-a7c2-bbb43da8b2fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde994af-3f3d-49f6-80d8-b5da681ae173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ac3c015-5b94-4d82-9ac6-07b9a1670dcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7941fd5-3852-4df8-8b05-733aa5351c53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fecada69-5f9b-46d7-a22a-6260c63a9de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a4b878-9c74-4303-be4a-231453302b18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3a03ae6-101c-4f40-bff0-02c5664663d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d85c58b-ac96-4604-8a6b-029d648925d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a91714d2-8c4f-4e64-880a-1762e4a24a27</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
