<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_StatusIsInTransit</name>
   <tag></tag>
   <elementGuidId>46e22145-124b-40b2-b212-6efe01d3433f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='InventoryTransfer']/table/tbody/tr[1]/td[text()='InTransit']</value>
   </webElementProperties>
</WebElementEntity>
