<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_DeviceType</name>
   <tag></tag>
   <elementGuidId>fde4ccc9-b87c-4474-b4c3-46071981ba4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='frmAddTransfer']/div/table/tbody/tr[2]/td[2]/div/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
