<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Target</name>
   <tag></tag>
   <elementGuidId>0fe2cd50-d0c8-4cbe-9263-c8915666ad7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InventoryTransfer&quot;]//td[text()='${target}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InventoryTransfer&quot;]//td[text()='${target}']</value>
   </webElementProperties>
</WebElementEntity>
