<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Packaging</name>
   <tag></tag>
   <elementGuidId>fa662b97-cb72-4b6e-9f75-f41d99ecb456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*/div/ul/li[contains(normalize-space(),'${select_packaging}')]</value>
   </webElementProperties>
</WebElementEntity>
