<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Warehousestock</name>
   <tag></tag>
   <elementGuidId>24e05765-599d-48d2-870e-dd62086b4749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Menu']//a[@href=&quot;/Inventory/Warehouse/WarehouseStock&quot;]</value>
   </webElementProperties>
</WebElementEntity>
