<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Details</name>
   <tag></tag>
   <elementGuidId>b5065de8-5c10-43ab-948c-33ba2bedcb03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*//tr[td[contains(normalize-space(),'${dealerNo}')]]//td/a[text()='Details']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*//tr[td[contains(normalize-space(),'${dealerNo}')]]//td/a[text()='Details']</value>
   </webElementProperties>
</WebElementEntity>
