<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes all the sales activities done by dealers from creating a sales agent, area and sub-areas.</description>
   <name>Sales Operations</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ddee4bb6-e654-4e9a-8fcc-ab8482e0bb0e</testSuiteGuid>
   <testCaseLink>
      <guid>26535269-2b3d-486a-9974-4c4e4fd627cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Agent/validate_AddSalesAgentRequiredFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b7a34c3-3ba1-4896-945c-fbc206b1226e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f350131f-b3e6-43db-82e7-df08cf45915f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1033180-7400-4ed5-8ed7-505e8765efb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42dd28ab-1b65-4172-994c-7ed0b2bba43c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be1febb1-e348-4239-9c6d-93cd44e82d82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Agent/verify_AddSalesAgent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8618282b-33f4-46d8-8a5e-0b1456e64486</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0b338c-9da3-469e-8890-01d1b5767e98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6544cf23-5097-409e-9619-38503b825d33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0897e1a0-d6ac-4106-9ea9-24cb2327f788</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0ec7fbb-c18d-4886-81df-b7b4cb06d11d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Agent/verify_SalesAgentList</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daad13b8-0734-4053-bd17-3b1c5e52cfb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78bf73b0-b3c3-4788-9d94-48129f600ed6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Area/verify_AddSalesArea</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1cd9954-17df-47fb-98c8-211de012d1b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f68ae50-4684-4fce-bf5e-d2407b297c2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c4de4ed-44dc-4771-a938-3391bd5c6caf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23864514-323b-4d63-9a7f-d3859d8d6b6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92e14b29-b0ad-4e15-a711-716447a8a37e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a193f1ad-db5f-4a0e-b31d-0f26e75c82c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Area/verify_ListSalesArea</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b870c2d-7232-46cd-b901-f55eda4d8fdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7fe6616-e8df-4840-8f72-9ff424e84908</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Area/verify_UniqueCodeWarning_AddSalesArea</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d33ab66f-f665-420c-8099-628289d0f324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae317be5-c590-4516-8cbe-6dbbf4e44a4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c56ac82f-4118-4a08-ba94-9fdd840e5336</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d17e4226-6d58-4840-a4ee-f0d2ef4b031c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9db62356-d585-487d-b025-5fb21cc30a4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b8643ca-14d2-4ded-a387-4ea2d2ffa35a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Sub-Areas/Verify_SubArea Added Successfull</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7bfad82-1dbb-4c6e-b7a7-bfbaa5533886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f26ccfb9-039b-47de-a251-ce604723dd0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fc93505-37bc-4c49-bb5f-8b1513713f8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a058d097-a5b1-4395-9514-a431d8939939</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3bd2020-cd7e-493c-b840-0b21010e1794</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Sub-Areas/validate_UniqueCodeWarning_AddSalesSubArea</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4a8a007-eaa9-466b-8bd4-905e8c47b464</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eeab7628-d365-475e-a77d-e145b9ee7af0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a45f940-ce6e-4538-bde1-a7cdb7fd65fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d87a35a-986a-42e6-ac4d-5075daa3d2a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59026d38-b137-44bd-89b4-ed5e2cd14d7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60b0c734-a7d5-4ee8-aa7e-00fcdb66b627</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Sales Sub-Areas/List Sales Sub-Areas</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
