<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_serialnumber</name>
   <tag></tag>
   <elementGuidId>d408ef7d-83dd-4f65-a2a1-38d9d72f6420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='UnitsToMarkForSale']//tr[td[contains(normalize-space(),'0118033201-000474')]]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='UnitsToMarkForSale']//tr[td[contains(normalize-space(),'${serialnumber}')]]//input</value>
   </webElementProperties>
</WebElementEntity>
