<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GetText_readyforsale</name>
   <tag></tag>
   <elementGuidId>8f1e85e5-1044-4853-9190-eebc8a9148cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='main-content-panel']/div/div/div[2]/div[1]/span[10]</value>
   </webElementProperties>
</WebElementEntity>
