<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executing repair pool operations</description>
   <name>Repair pool operations</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b3df1127-077c-45e9-b78b-f2b5361cdd89</testSuiteGuid>
   <testCaseLink>
      <guid>fca999a3-36bf-43a5-b286-735d252031ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_Repair process</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b38bfd68-f25c-4ee7-b8cf-07cead7a8020</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d20dfa9-8741-445c-a036-2903d1c47524</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f302fdcf-24a7-4fb6-bf7f-8f4e76c84114</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e57ed21-eee1-453e-b2a5-01a0a4ba2bdf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Repair Process</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>182d19f3-5c5f-42a2-883c-42d6b3aa7e5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d579f3-7fc3-4d7b-8860-e479385888b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f4fe6ab-9187-4737-a5ba-8240e06c5ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>884522ab-9edf-40e2-8a00-5ed3e8156f7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5031cf1-43cd-45ee-a843-211f0a3a261a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb7907d8-258e-4f2d-a0e1-699f3945f52a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be82098f-4b9c-4d3d-bc8c-9d6296692417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_resolution field is required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34aa644f-39aa-4696-883f-01e59c04d43b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f81baf7e-4014-4c44-9c00-a6bab61f1fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fab0719a-0b64-4ea7-8c89-aa85206eb992</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27ae9e40-08d2-4c94-9c30-c266df8ea840</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_blank fields for repair returned device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb8a786-1fc0-4c2f-ba34-317f5f0424e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae8ca94b-2ca6-4c5c-9748-014446e5f131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a333905-aab4-424f-9508-dd6d0b44fb26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a447fd32-e61a-4bac-af1e-3ed23ad2a592</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eba9a7ed-0049-4617-86ef-5817df6e59ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85d7e7c6-5be8-4c62-a9e8-f1a5f57a4cae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Repair returned devices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92861f34-f8ac-4b2d-837b-bd5d75e65b2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a041bf62-ba62-497f-8d57-0dd9f28a8181</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d521269-fe53-4dd8-af84-488823505190</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbfef6f7-e259-4c48-9b69-348e2e0d1725</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ccd3fe-ccf0-4c4e-b386-87ac95271b96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>353fee73-2e0f-40d5-8a7c-5d69b0865d56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_blank fields for approve device repair</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5b44311-0644-459a-90c3-19a92d831eac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1912430-5a35-451d-aae0-214f583bffa5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61b2458d-ee4b-49e8-afee-44a0b4218ffb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c938483-f20f-4b63-a11c-c2c5be86c2c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/validate_Approval status is a required field</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>857bc567-9863-44bc-860f-29aa05d354ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c669759b-4890-4b2e-8c52-963123c9a09b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89de60b4-0e18-4065-bc54-19da8bd1de6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool/verify_Approve device repair</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb67a162-75c7-4f53-8411-597641352122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc182a92-a511-4c42-9787-2354e139150a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e77f96-98f5-46b7-8036-146cb6d9f1fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>461b9647-5ac0-4945-8448-a4d42bcf0e71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool Transfers/verify_Repair Pool Transfers Out</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f78c998-731f-4090-b10f-b65368da0296</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddbfb64d-7d24-4c7e-9a4a-2c654b786dd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3ce3c04-c215-4ebe-beb5-89d990f9ec4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112bf9ea-f377-46c6-83b2-31705d41219c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8547c393-065d-4bd2-9d79-a227985ef124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1c4910b-d26c-4f9c-a2f9-b0883fd77101</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e918e14-4ccc-4f54-87ea-14e8b038a8f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Repair Pool Transfers/steps_Repair Pool Transfers In</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee1c82a-d3b2-4f00-95b0-f46ea4e1669d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17150d63-b3d7-4378-9b16-a39b6d66c35b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>453be2a4-71c9-4efb-bb1c-17b7bf99b370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9059b29-d4eb-416a-b245-e30c7e884a4e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
