<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes all the operations for AddOns eg: sell addOn and Cancel AddOn .</description>
   <name>Add On operatipns</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>44ad2c79-d66e-4b70-9a86-4876af6f1c8f</testSuiteGuid>
   <testCaseLink>
      <guid>9b5b0a4f-d10f-41e7-af62-580bc586a9f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Add On/verify_Sell Add on</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce1cedcd-12e3-4b0b-b4ca-63b1bf4b922a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85a33584-734a-4905-9d24-888b080ecf25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6642837-5193-405e-af27-d2f94851cce0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48b00d7a-00b0-46f4-bfa5-608f89f72c41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91f950b3-1560-4991-b5c8-5b56a6455f48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dffdeda-c4f9-43df-a349-00889202cbda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9ee8cc6-cc5b-4465-b18a-38ef5218c2da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5b637f6-0945-463b-a5a5-e15cfa5e39f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Add On/verify_cancellation of Add On</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd184a5e-edba-4243-92be-c9d792833b54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b4909ae-bd19-4c94-9c69-828449bfaf26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19100add-fa2c-40d0-b53e-3402f52deab3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08041464-9b5e-45e2-bbb9-9366db85d672</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3677d40f-ab4d-4941-b0aa-5fd7c08a63a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Add On/verify_approve Add On cancelletion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68e1dec5-e00d-40dd-bf88-31f1c38a8c97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e19d30a-b5aa-41a1-abe9-f78a224d6a38</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
