<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Approving device direct swap</description>
   <name>Device direct swap</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>205a7c26-cc67-405c-8c0e-07bdb9c8be5b</testSuiteGuid>
   <testCaseLink>
      <guid>afcf7f57-a953-468e-9280-2725153ec60f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Initiate Direct Swap/validate_Reason is Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9757973-4348-4290-9ff6-76a5bfa98f3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c9b9eac-76d0-4427-89c2-05a31fde1df1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5650cd4-9306-4181-b2d9-8f994f0f96db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bcbd1020-ac2e-4b36-ae3e-7834151111ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Initiate Direct Swap/validate_Select the Bundle Item you want to Swap</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a0595d-d73c-4c27-b1b1-2d375e712a69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f83c5e-5cfe-43cf-8f45-c6f716e56ef3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04924c6f-730b-4faa-8479-b88a5c4a02c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a82ec744-21a6-4838-a6bc-f81c50634082</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Initiate Direct Swap/verify_lnitiate Direct Swap</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ee8410-a279-4351-a301-5c2d761d7bea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ad965d-2a88-4c1f-a396-e9064e310cc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb0167a3-7dfe-444c-b2ef-1306f0f939a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16d33d4c-720e-4f55-b637-8e978c1280d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Approve Direct Swap/validate_Approver Notes are Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7108797-cfdf-4598-ae89-72101efc9eac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>217c9e35-675c-4004-8fd6-91325a13f40a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e59fca2-23ec-45e9-91c9-ea8d2697520d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0079e292-bb1d-4c8a-aa5a-0378d6df070f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Approve Direct Swap/validate_Status Value is Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e1e2dc6-afd9-464a-9133-1a6503722ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dbc00d7-0b7e-4734-82ac-ca36c5071934</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62563e88-8085-4625-9604-4eb89551ff1a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b2858a8-929a-49cf-a906-7dc27e99f41f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Approve Direct Swap/steps_Approve Direct Swap</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c28c0d68-99ad-4e2d-a901-adce48fbc83b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ce8bc35-bbab-426f-92f5-667aec98a3c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8b72c8c-0c4c-4a53-90af-b70b2db8bad2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5600258-0b40-4f41-9a3f-69d0335aa14d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Approve Direct Swap/verify_Approve Direct Swap</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4570858-2e5c-4233-ac19-eb49db739234</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ec7a768-c7cb-421c-b1ff-b6dce23b77a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b198857e-4030-4724-a87d-114931eab931</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
