<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes opreations such as sending credits and states to an m-kopa IV  device</description>
   <name>M-kopa IV device</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>140844a3-b5e6-4d4e-9d4d-9803947a0cd9</testSuiteGuid>
   <testCaseLink>
      <guid>6c90be8d-9003-4072-86a0-8532af389f8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Sending Credits to Mkopa IV Device/verify_Sending Credits to Mkopa IV</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41988d06-5061-4780-899d-8af9f2242a1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0c6473-f4fc-47b1-95e1-374e683d2bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffdf0bc2-b5f8-4e13-8372-30a9f6c8424e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2c110dd-6490-47d9-acb1-0ec586fe9cee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e05fc90c-9e30-417a-853a-d1cf526097fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adb5004d-ca02-49b9-a98f-40a04fe9cb32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46b1296c-2233-4751-a12b-2a82d91849ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1ffdcd1-544f-4f16-b511-4446d2b568f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Sending States to MKOPA IV Device/verify_Sending States to MKOPA IV device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5b7c26c-d23a-46b8-91dd-af584f8b7937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb942b86-2a98-45ad-b42d-8e83e1397934</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d1b72c5-5428-44ed-b37f-aba23e1517db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65bbf880-ff10-4e8a-bdb9-cc8e476c4dc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ad7616f-80fc-45bb-ba9a-5d65a8e76892</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db5d99c7-65a3-444e-8055-95b3171f5410</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>695d377b-1612-4533-a6a9-93abe8d36714</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40d7ef84-5232-437b-b030-23e8beaff5cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5b4e215-2d13-413f-abc4-e2b2e1af1538</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/View Credits Sent on Credits Sent Tab/verify_view credits sent on Credits Sent Tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3995730f-52ef-43e2-bf2c-b7c5b90390bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04d8dd11-9d55-4886-8824-a88bafb0b32c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb02dbbd-e20e-4a3b-8b85-8e34fb363e27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30715f6c-0837-4672-bcba-b211b5953ed7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34959819-3396-4795-a961-10cf281d4355</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
