<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Making an upgarde for an m-kopa IV customer</description>
   <name>M-kopa IV upgrade</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6e320646-21f8-4fb5-a58e-8af4d7ffc49c</testSuiteGuid>
   <testCaseLink>
      <guid>3b9f4c79-dc2e-43e9-a44e-27608b26ff49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/validate_FinishUpgradeRequiredFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae9e071e-0cb5-4345-a998-b477155a58e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ea72cb2-5bf1-46ce-b103-41d2b9125aa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3365da4-98a6-4a7b-b250-0eb163369e96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2885824-7c87-4800-9863-56cf4a203964</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/Validate_MKOPA 400 Upgrade_RequiredFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95849d0b-c557-4016-90d0-d0dee27c4580</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ffee59-0c24-453c-b8cb-50f0dc27b147</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8b8a325-96ca-41d3-baa6-acf5aa851173</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/verify_UpgradeLinkMissingInNFP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f449ad90-6426-4c1f-b432-4f0fb24e5b5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a29b2feb-e096-4eae-87cc-f5c68c9198d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>992f441c-7540-41dc-8c75-fa684192cf16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/verify_UpgradeLinkPresentInD10GProducts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145b4600-f772-46e9-bc3c-20a8151aabcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43abf6df-f831-4f9d-ace6-4c5fa1e84103</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/verify_UpgradeLinkPresentInLoanCustomers_Existing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30056ef7-33f5-427a-a917-3dc07ddbf780</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75eb7058-b263-4d2a-8056-91689aeca323</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/verify_UpgradeLinkPresentInLoanCustomers_New</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07c0592a-2c6e-4456-bce0-77566ac4248b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d521834-791b-4091-a210-fa16c7c0f0be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b55dbca0-3e76-42ca-a7fa-3aca93c2cf36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e43dfe4-02d0-4b47-8ef2-b5d6a4b52876</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f398d042-21c3-43b1-b457-91f6ab3fa308</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/verify_UpgradeLinkVisibleInFP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e353cf3-423f-4f22-b0a7-1c4e0cd4842d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f5c5e7d-287b-45be-aa2b-14f5f458bd96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a22e7b0-f0f4-4d6b-a580-3a91fc362d04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/MKOPA IV Upgrade/Verify_MKOPA 400 Upgrade</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95ecf768-4f64-43bc-ad03-dd5886a93498</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>521a576f-fa86-48e9-ad40-a8b9e54c5c51</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
