<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Execute adding an oulet product to m-kopa IV device</description>
   <name>Outlet Product</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>80042441-680e-440c-bd48-563ab41925d0</testSuiteGuid>
   <testCaseLink>
      <guid>926542a9-8761-4db3-8d11-789f85d31458</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Outlet product/verify_ Outlet product approval for m-kopa 4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e62198-73ee-4b49-8013-3c69448dc487</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e4738ce-d8e5-463a-86bc-b808d83a3948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fd8c275-deec-4d7b-878a-721c65202a82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e13a9a82-caa9-40ee-8c6e-ed0b2caa7fb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>385ab79d-e5bf-4bb7-94ec-5ffc228c9445</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35ffd241-60b5-4475-b5a6-9431f5eb1056</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/MKOPA IV/Outlet product/Verify_adding M-kopa 4 outlet product</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18208813-6cbd-45d4-b48d-f35f70ba5045</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c1c3031-f151-49bc-bdd3-6ec5e6219d3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a41b8343-f524-4306-8f04-5b3c264f05c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec49ffa3-ef5c-4ab1-9eda-60f5423ac701</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f156417b-9a60-4e83-92bb-f3b516f887b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5986a5d-0a3b-4fc2-b4e8-bf10a34085e0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
