<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes operations that involve warehouse stock</description>
   <name>Warehouse stock</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>dfd3657f-7c56-4e17-b9e1-9416b119a641</testSuiteGuid>
   <testCaseLink>
      <guid>cd14c219-d646-42ab-960b-177fd73b8786</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Check Stock/verify_stock mark as ok is processed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e4220d0-1fd6-4563-92ca-b02c9d9de77a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4da1cb6d-5714-4003-9515-50d436a8c59e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0878b19d-904b-4ac4-9226-9cc029314187</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1acad8df-a46d-41ed-bdb4-a7065e552e45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67e2d0ee-862a-451b-bf8a-4f253f49b00f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Confirm Cartons Ready for Sale/verify_marked cartons as ready for sale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bee5517c-4500-4b6b-b46e-41551860cfb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86a39095-83f1-4e33-b8e4-3549436fef72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d68051ef-0039-48fa-ab7c-2972496f2612</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05ab05ed-7dd6-4b1c-9597-f71a72408c45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0113e47a-c0b6-4017-b212-a1763a637f70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecc420db-8712-4879-a24d-923bf2330a37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Mark Stock For Sale/verify_stock Marked for sale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2af24020-dc25-4ad5-971a-34aa25407510</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d4a225a-c46a-4eaa-9910-b1b6016ad702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ebbca8e-0c94-42bc-aadd-e858e2ec9f1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>861f087d-f664-4776-9bd4-70d9ba81a33d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03bb9a92-a442-4cff-863f-83c9d2cdc8d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Units Marked For Sale/verify_Units Marked for Sale</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fda5714a-c3ce-4171-ab38-fec644565f5d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
