<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Manage Payments</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-08T14:44:40</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>65d3925e-8d52-4237-a4d0-61ddb9b112d6</testSuiteGuid>
   <testCaseLink>
      <guid>6fa66e93-0973-43ec-89a2-7263edb9bebb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Customer Payments/verify_Customer Payment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6024dd6-cf55-4095-a04a-66505c2b2692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>821d9392-8119-42b4-b1fb-0f21005337c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056f2335-96ca-41d3-9ffe-e2c4678edb82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bafc285f-cc27-47a7-8815-2c4980340d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3a1123b-425a-4a32-ac71-b01ba886f95d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Customer Payment Notitfication (SMS)/verify_Sms sent on correct amount deposited</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85bb640e-291e-4c6b-b637-a7f626c12694</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cba0f0c-a789-42cf-a19e-e032cfd102f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837ea428-a633-4764-950c-5a29b18a4e27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ed97df-9eef-47cd-bd1d-24048598cb98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b0594d-d7b8-43e6-8ab5-dc701843d8e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7b25927-685f-4b2f-b8da-5f9e5a79037a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Search For Payments/Search For Payment Using a Receipt Number</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4245c0a-e8cf-4c6e-8a35-b9cd38e0121d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
