<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>managing outlets operations such as adding operators ,otlets and products.</description>
   <name>Outlets</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>dfc18e7b-01ea-4682-983d-0c33b19713d3</testSuiteGuid>
   <testCaseLink>
      <guid>f1a14e18-18c0-482b-ba60-fda4f13e17dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Outlet/Validate_Adding an outlet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04a52552-40a7-4b36-9cba-a6cc61a6ee8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d1f1938-8388-4c50-be96-99adb7e09609</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Outlet/verify_Adding an Outlet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a3099c5-243b-4a19-b24e-6a75170c32e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>380e75b2-1c45-4bdc-9e46-5b2c1881c95a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>750ceb78-695e-4d59-bd56-1003b76e8e6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b218d762-86ea-4280-85d2-c0138be9fe83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e994004-9ae8-4e7a-9dbe-69243e2dce6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ec9675-ba80-4cb3-b17a-150956044be7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfa82531-192b-48be-9923-804607131b54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3485c189-d345-46ac-9f64-15cb396b1458</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5824a30e-fd07-4e34-84bd-bc4348d6ddc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fb4a0c8-a530-4412-ae7f-d7ec130cada4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42fea436-85ab-4e71-b333-bece140626f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6753cc8-b745-48ba-a00b-9e30e74c629f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>832d0e46-5bfd-4e32-9aea-a3844d93e9e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20e52574-c376-4d9c-9c75-ea42dc3445fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e489077c-01c9-4d9c-a658-40d18e660270</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Outlet/verify_Confirming outlet added</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e9b52d2-e093-43d6-b200-b8ad34a5de96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07c0d00c-17f2-4e2c-9388-e0fc6f43c817</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3773000e-a9de-4fe6-9aed-bc2290bf6082</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f6b2ae0-333b-4f18-a5cd-69088c5ebbbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e237916-261a-4e47-9460-a2a7c16b37d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d3e3861-80bd-4d51-8715-d19b13cd6575</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d24cc5ba-9792-4699-821a-7d3fe54cada9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5726415d-b914-4ba4-81c5-beb6e9a45ffc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f673b67-3dc8-4d43-896d-0c4fc25c7fee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e46d6b91-8b15-4cb0-82a3-86f2e91e24ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a1212b0-3159-4f36-bc66-9d4926924c13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cb94e64-351d-4d80-b344-66d269d20c13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad633400-0dc9-49e5-9948-1c9081ed1146</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff788387-0925-4eba-a6cd-ee5446a013d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>692f9d35-d8d8-479d-90ed-5b77d1418016</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Outlet/validate_adding outlet operator</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c964750d-2221-462b-9447-820e0cc55df8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e4de7e8-7545-4bbe-a47c-03a05a368064</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Outlet/verify_Add Outlet Operator</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9e877ce-067b-4861-be1c-9f960c87bbdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba8e7a55-068e-4653-bc59-7608d882a0a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74534c09-094a-437e-b9b2-66dcc76a30c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86bd4d05-6cfb-4f2f-8cb9-28220e2c3100</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c67d88-8e71-468c-b5e2-6ae444ee669b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba77dae7-ed60-49fc-90c8-98493d7e8ce2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3747777d-9ca6-4900-adb2-388974072fd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a24d87-80fb-4cad-868c-b355b4e67402</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cbf6f74-91d2-4d4a-bb95-5ea0ab908afe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>767c7522-79ee-4cf7-bac6-7a63d9ad8cc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c189cee-756a-4e31-b99b-559f5788b1bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Outlet/verify_Confirm outlet Operator added</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9caa6872-eddf-4b43-8457-1d9ef3976549</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff2f0732-1e21-4191-b438-3df271715f8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Outlet/verify_Add outlet Products</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a41f526-350e-41e4-961a-957c35818b90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28fad19b-1b5c-4d3f-83a4-5ef1506b965a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f786e9d-bb0d-4dea-940a-ddd5b6c4e055</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16bff537-3395-429e-bf45-64af81a50b07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Approve Outlet Closure Request/validate_Approver Notes are Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>687bc5b3-97f3-4347-ae2d-be1898ba5d1a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30a44571-af66-408f-b9c2-b34f03c2007e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Approve Outlet Closure Request/verify_Approve Outlet Closure Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d5c5721-e4f3-4d9f-a441-c367980d5de1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc0e5183-cd22-4750-8c75-951cbcf120ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5696027d-8751-4e8a-bae9-94d9fd1cdb5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e4ba3a1-32df-4b6c-a1c1-809345758f4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Flag Dealer As A Service Center/validate_required info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8593a9a8-e996-4a6f-a18c-402b90ca12ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99526a67-3f1c-4e1c-a1ee-0ea4746fc896</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Flag Dealer As A Service Center/verify_Flagging dealer as a Service Center</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>126ae66d-ed62-4770-a732-e4c3838b9f9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12b790db-822a-485d-b3ba-6e7dce942d91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55b64f22-bb1e-4c80-9323-48454ebe1d9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>febc2a9e-0373-4292-a3ff-46c3b21b43b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Flag Dealer as an Agent/verify_Flagging Dealer As An Agent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30fe14bc-2c62-4e39-a1bc-d6f3306d0c0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cdcd858-d3f8-4202-9319-9a7dc4f03113</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d89062f-e0e2-48e6-b0e3-b6fbc1760161</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
