<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes all the operations done on D20g device</description>
   <name>D20g</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e747778d-6d8c-4460-abd9-bdbb1f40709e</testSuiteGuid>
   <testCaseLink>
      <guid>dbe73b25-93fd-4bac-815b-0276a059d03a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D20g/Send Credit/verify_Send Credit Manually in d20g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df5b54a9-b5b4-470c-845d-7a5b80299900</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d4282c-cb87-4965-bcb4-08ccb05c3445</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaec796f-8171-429a-8e99-8e8421b0974a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13ecffd1-6a89-4aee-8cbf-7fc6cef5b075</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bdcb9e6-bf1f-4981-be85-038e01d07a3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c48a950-08c4-4fe6-bccd-a4b37d6c0e81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e12a5905-7000-49a3-b2bc-dbfd4cdd0b5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f65221a3-a17b-4e2c-824b-598e4c971729</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D20g/Send Credit/verify_Send Credits in d20g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae7edd06-c30c-440f-a635-9ede0095ce21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51e6850e-8776-4d18-a344-81f125e9f33f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b60d31b2-1fad-404a-b77f-8320a3647543</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6096375d-ffbf-4a70-872c-2cf48c8a7e68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D20g/Credits Sent History/verify_Viewing Credits Sent History</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c83e2e4d-11a6-49cc-932c-20919b8b061e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00e18692-5ac8-4c01-a7c8-3e862a93b8a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03e81abb-73b3-44fd-8ddf-baee25d66a21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14eee5ce-d076-4ac4-8573-027661b637d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33f1b368-f857-4bdc-86d6-52d36a36d170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebe17ecd-1084-40ea-adea-1090dbb60278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>457d5c1d-de32-46f6-82c9-529426f28ff9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06a2aab3-e30a-4121-8f4a-7612d4a729a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D20g/Send State/verify_Send States in d20g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38da6fd3-abc0-4da5-88ec-1af3583f87a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>252fb612-9d4e-46d7-af90-e83e7dd683ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab5ce4ff-6373-44ec-b556-6a683132b9a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a84dc7c-1d24-42b2-bb46-05676192015c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2043b216-aa51-4ee3-9be1-c13c683522b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f192f814-1db8-44a1-ada9-9a7568decb86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56326671-551f-4ed9-beff-4ff5ce0b4eaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2edcf15e-662b-4db0-a949-b6f4fa556ea4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9840070c-0d48-43c3-a98a-9e402188bad8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D20g/States Sent History/veriify_States Sent History</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2171a26-0d75-4881-9059-a90d1046da14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>befef4a1-ec7f-43ce-8284-6efbcc8d15fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8385a3ca-4587-44b9-afa3-d065e18f2372</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d96de7-3837-4696-9a5b-81ad77dc18ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1193d84a-af4c-4f44-a2f9-0636a801daa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4401e78d-f170-47c8-a12d-26c9157cedaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32fdf3fd-33ae-45eb-bbc5-56032ef15646</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e88295a4-ef59-4f51-8d6d-7b64d525ae4d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
