<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Gender</name>
   <tag></tag>
   <elementGuidId>7967cf9e-6ed7-4218-90d0-69a5fb123c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyMain']//fieldset[1]//tr[4]/td[2]//span[2][contains(.,'select')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']//fieldset[1]//tr[4]/td[2]//span[2][contains(.,'select')]</value>
   </webElementProperties>
</WebElementEntity>
