<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Dealership</name>
   <tag></tag>
   <elementGuidId>9aa26050-d3dc-4b58-a5f2-f7cf66644468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']//fieldset[3]//tr[1]/td[2]//div/span/span[contains(.,'select')]</value>
   </webElementProperties>
</WebElementEntity>
