<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Language</name>
   <tag></tag>
   <elementGuidId>16a4dad7-7add-49c7-8843-0346ca32020b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyMain']//fieldset[2]//tr[2]/td[2]//span[2][contains(.,'select')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']//fieldset[2]//tr[2]/td[2]//span[2][contains(.,'select')]</value>
   </webElementProperties>
</WebElementEntity>
