<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_PaymentPlanType</name>
   <tag></tag>
   <elementGuidId>b34728d0-bb74-493b-965f-33c4a7917994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyMain']//fieldset[5]//tr/td[2]//span[2][contains(.,'select')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']//fieldset[5]//tr/td[2]//span[2][contains(.,'select')]</value>
   </webElementProperties>
</WebElementEntity>
