<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_OutletProductType</name>
   <tag></tag>
   <elementGuidId>cfe756f5-65be-4d3f-8e97-f5c20c6ae195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyMain']//fieldset[2]/div[2]//span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']//fieldset[2]/div[2]//span/span</value>
   </webElementProperties>
</WebElementEntity>
