<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_returntype</name>
   <tag></tag>
   <elementGuidId>3b69e137-5648-40ba-8a0d-1fa83e041f0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*/ul/li[text()='${returntype}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*/ul/li[text()='${returntype}']</value>
   </webElementProperties>
</WebElementEntity>
