<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Outlet</name>
   <tag></tag>
   <elementGuidId>29402b13-004f-44eb-9deb-7ed72c8392bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*/ul/li[text()='${outlet}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*/ul/li[text()='${outlet}']</value>
   </webElementProperties>
</WebElementEntity>
