<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_DeviceType</name>
   <tag></tag>
   <elementGuidId>2869a69a-3527-4175-9be1-073406f1ef4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[1]/div[2]/div/div/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[1]/div[2]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
