<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Packaging</name>
   <tag></tag>
   <elementGuidId>5f5cfe92-22c4-437b-b7c4-47b0d15c2650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/ul/li[contains(normalize-space(),'${packaging}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/ul/li[contains(normalize-space(),'${packaging}')]</value>
   </webElementProperties>
</WebElementEntity>
