<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Details</name>
   <tag></tag>
   <elementGuidId>2b3c9d20-50a8-41ab-af36-e4d5d37c3ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='LoanPaymentPlansGrid']//tr[td[normalize-space()='${planName}']]/td/a[text()='Details']</value>
   </webElementProperties>
</WebElementEntity>
