<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Resolution</name>
   <tag></tag>
   <elementGuidId>eb441dcf-c2fc-4c28-8bad-04b38ed871f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(normalize-space(),'${resolution}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[contains(normalize-space(),'${resolution}')]</value>
   </webElementProperties>
</WebElementEntity>
