<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_approveStatus</name>
   <tag></tag>
   <elementGuidId>c8153239-63db-49fd-8925-4623d8025676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*/ul/li[text()='${approvestatus}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*/ul/li[text()='${approvestatus}']</value>
   </webElementProperties>
</WebElementEntity>
