<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grid_salesrepallocateddemo</name>
   <tag></tag>
   <elementGuidId>d1c29895-c536-4882-b50e-7b49b86d358e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DemoDevicesList']/table/tbody/tr[td[text()='${SerialNo}']]</value>
   </webElementProperties>
</WebElementEntity>
