<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Approvals</name>
   <tag></tag>
   <elementGuidId>2a4b77e1-b19d-4d52-b02c-ea3ed6b5e6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='Menu']/li/div/ul/li/div/ul/li/span[contains(.,'Approvals')]</value>
   </webElementProperties>
</WebElementEntity>
