<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SubmitAddProduct</name>
   <tag></tag>
   <elementGuidId>8077c642-1eaf-4fef-b5b7-c8954de773f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='upgradesForm']/div[2]//div[@class='div-strip']//button[@id='btn-add-product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='upgradesForm']/div[2]//div[@class='div-strip']//button[@id='btn-add-product']</value>
   </webElementProperties>
</WebElementEntity>
