<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_PlanType</name>
   <tag></tag>
   <elementGuidId>93e29e31-bd80-4d12-96f0-b46cce19156e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;frm-add-product&quot;]/div[2]/fieldset[2]/div[2]/div[1]/div[2]/div/div/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;frm-add-product&quot;]/div[2]/fieldset[2]/div[2]/div[1]/div[2]/div/div/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
