<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Outlet</name>
   <tag></tag>
   <elementGuidId>72d83b25-e39b-4534-bcc5-306c470322a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='frm-add-product']//div[contains(normalize-space(),'Outlet')]/div/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='frm-add-product']//div[contains(normalize-space(),'Outlet')]/div/div/div/span/span</value>
   </webElementProperties>
</WebElementEntity>
