<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_AddNewProductRequiredFields</name>
   <tag></tag>
   <elementGuidId>25003912-9ea8-47fa-92ad-c4bd4005d1f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='frm-add-product']/div[1]/div/ul/li[contains(normalize-space(),'p')]</value>
   </webElementProperties>
</WebElementEntity>
