<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_FinishUpgradeRequiredFields</name>
   <tag></tag>
   <elementGuidId>87a0447d-36f9-4c8b-b681-b3a666c01186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;divBodyForm&quot;]/div/div/ul/li[contains(normalize-space(),'Please')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;divBodyForm&quot;]/div/div/ul/li[contains(normalize-space(),'Please')]</value>
   </webElementProperties>
</WebElementEntity>
