<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Dealership</name>
   <tag></tag>
   <elementGuidId>d1b1180d-7f38-4072-821c-d5868e4a2e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[13]/div/ul/li[contains(normalize-space(),'${dealership}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[13]/div/ul/li[contains(normalize-space(),'${dealership}')]</value>
   </webElementProperties>
</WebElementEntity>
