<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_PaymentPlan</name>
   <tag></tag>
   <elementGuidId>9354da1a-f47b-466a-aa46-f11618e28489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[17]/div/ul/li[text()='${payment_Plan}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[17]/div/ul/li[text()='${payment_Plan}']</value>
   </webElementProperties>
</WebElementEntity>
