<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Outlet</name>
   <tag></tag>
   <elementGuidId>6691f6d1-0c36-4b92-bd02-3784cab8711c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[14]/div/ul/li[text()='${outlet}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[14]/div/ul/li[text()='${outlet}']</value>
   </webElementProperties>
</WebElementEntity>
