<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_PlanType</name>
   <tag></tag>
   <elementGuidId>5cb11edb-b6ea-4fe7-9593-abbc9791af87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[16]/div/ul/li[text()='${plan_Type}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[16]/div/ul/li[text()='${plan_Type}']</value>
   </webElementProperties>
</WebElementEntity>
