<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_ProductAccount</name>
   <tag></tag>
   <elementGuidId>266bb9ca-385a-44b8-9755-992a060dcb0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/ul/li[contains(normalize-space(),'${old_ProductAccount}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/ul/li[contains(normalize-space(),'${old_ProductAccount}')]</value>
   </webElementProperties>
</WebElementEntity>
