<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Operator</name>
   <tag></tag>
   <elementGuidId>51c9a630-6320-4f78-9dc0-46ab1307cc73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[15]/div/ul/li[text()='${operator}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[15]/div/ul/li[text()='${operator}']</value>
   </webElementProperties>
</WebElementEntity>
