<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_warehouse</name>
   <tag></tag>
   <elementGuidId>3ba4cd50-aa5f-410c-83a8-455e838d49dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@value='abe06b87-e217-e411-9438-000c29921969']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@value='abe06b87-e217-e411-9438-000c29921969']</value>
   </webElementProperties>
</WebElementEntity>
