<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Operator</name>
   <tag></tag>
   <elementGuidId>864c075c-904a-4ab7-b187-ce7adc2bcc39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*//li[text()='${operator}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*//li[text()='${operator}']</value>
   </webElementProperties>
</WebElementEntity>
