<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Filters And Sort_Dispatched Orders</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c8f9ee38-cd07-4277-86c2-302872343de5</testSuiteGuid>
   <testCaseLink>
      <guid>c0bd1ff5-fe14-4c77-9787-c54a591e0533</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByDateDispatched_IsEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a22243d-08e2-4886-9c40-6b8dfc79c4cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>462a5274-c666-40bf-a8e3-ebe440158653</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1566ce8-56f0-44f3-82b4-8a49c9cbb44a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByDateDispatched_IsAfterOrEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72a842aa-6a66-4183-959e-d008290d292f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90b51db2-663c-4325-943f-c4956a0dc5de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b4ac902-b31b-4ad6-9806-c4d8e9f19ba5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7273b83-40b0-4e1d-9e48-f8f4491682e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb8f86e4-58e2-4a6b-b23b-69ce7445f5c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByDateDispatched_IsAfter</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2e0f581-3acc-4a9f-865b-ac6123e9b074</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eaa18f4-a0b3-4b88-a23b-5000add65e67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82b2608f-117c-4ac4-964e-3f3fd0b06b1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b6fbc5-45b4-4f4b-929c-2bba7edc0f9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d557f64-d85f-4083-8e9e-5e9a46e3b441</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByDateDispatched_Is before or equal to</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47b15d60-c6fe-4339-9e65-d3f77de65d04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db6a896b-b658-4c5d-a904-40aedbceb295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03b212eb-2c17-44af-9b63-12191ee29ae9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce8085ac-2358-40f0-8396-f1d9f4cb46ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>545b98ea-7701-4e68-87c8-98019d8874e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByDateDispatched_Is before</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8fd6bd4-260b-4e39-a0f4-1f9e9a12f96d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60c43781-2c39-4ddc-8919-67f0e1117917</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc212ad7-0caf-43ba-a39c-d44870bebfce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbb4ff8c-48e0-4061-b5e4-19bfae356642</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e416f125-98b2-4921-a1f4-d94039f95e18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByDateDispatched_IsNotEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b636c70b-089c-41a5-acd7-8db8f1cb19b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb9ee62b-83ff-41dc-8ae5-a8f9ddc5d50e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9917340e-86d4-459e-a2e7-cb55b9113ad3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fb13a7c-2864-46e7-bf43-fbde1d8fc7a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca677d2c-00eb-4c9c-9742-c09c50729dc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderNumber_IsEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63d51c46-0889-4836-b475-94e085e88b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0f8be88-559c-47ba-bf65-d44ba712bbb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68385326-d65f-48ce-b482-f470c3d48153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderNumber_StartsWith</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6bd5927-942a-4968-b7de-d6981a04148b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7931a5cb-eda3-4c24-855b-f7686cd7ac25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ec0daec-e175-4f02-ad2b-9a809f7dd25b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03738ad9-3fa4-4cb7-a19b-27387c590017</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>068ef00a-6be3-4c30-a53b-a79f1d5fe948</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderNumber_Contains</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76620b43-e093-4747-a3ea-50a70b40288b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bde9eb34-179e-42d9-bdd6-b890c779fa6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6254901c-5ebf-4d96-a56d-f0fe726d3a86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4d12bb1-dbaf-4c5c-b592-bc14012ffb1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90b09075-fae3-4eda-ba59-3e95a0ac480d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderNumber_DoesNotContain</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67b4d3b8-be7d-43b2-88a8-236a655f76ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56346351-f3bf-4f14-85c7-b9ae6373d0c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b381458e-f078-4f3e-820e-79e5d0e9eef6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bffbd7fe-5f63-414b-86bc-9a014e864a7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderNumber_EndsWith</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef4241a1-6fd0-4234-a8c5-447ee72a18e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b813c858-f9d1-4fa2-ad4f-d315d95c1e24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b611f939-05ed-49e8-88df-5787136b43c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1d00e61-8d66-424c-a6a9-48401f063504</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edf0cae6-d2a1-4562-9524-a79cc17b437b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderNumber_IsNotEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4659f514-a35d-40d3-a0c1-bd844f4b7528</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae7d6b84-7d74-4211-bc89-5037d3bcf1de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a38e6d6a-7b97-4e95-9c80-1c481a2e80c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e1901da-149b-4233-aaa8-2120a6aaf259</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderingOutlet_IsEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbdf9563-c1d8-4994-a572-9b3eaeb61698</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bd9bd2d-1b39-4443-a2d9-0efe1a5e75d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24edfee0-9827-4e43-aeb6-97476d082b14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderingOutlet_IsNotEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd7e074b-7b07-4e1e-8c2f-1fc0a8d531d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9f695ea-3994-4a39-8e85-36e25623be61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09ffc83b-8035-4999-8b0f-f16689833ca1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08ee463c-ae6f-45c8-b85c-34206fe97233</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrdeingOutlet_StartsWith</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5afdb2e7-737e-48f4-bea5-a0e4ab03eb5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f0062c8-64af-4ddd-a647-e28138661903</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f060c157-0fd9-43aa-8921-99af64e71be8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa53eade-39c5-4b92-a84e-bff16b47164f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b9e4a50-8475-4a03-a9aa-dc0cea35c509</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderingOutlet_Contains</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5977defa-63b2-4bf4-91cc-3457bf86c386</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3745d285-9824-4427-b93d-d14b9e1b6c6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>549d9a98-2a8e-4c5a-bd1a-f0e75cccac7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>896c2ae8-c891-40f5-9eab-31d543bb2869</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bd54405-18be-45fd-8b89-12dea5d477d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderingOutlet_DoesNotContain</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcabec92-e523-4b3e-973f-e719c73cc3a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36037f5b-f026-4e65-a515-2b0d85639746</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51ffcbc8-eda7-4e6b-98bf-2acd44a8a6be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bedba58-b96f-471e-9775-a16fe208f4f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByOrderingOutlet_EndsWith</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed8ccbbf-999a-422f-88f2-7e09a5a121de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b872dfe5-c30a-4f86-a019-d6f26285e9b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02d88263-945a-4162-b4b3-21ea36ae4227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5a40af6-2bc4-47f3-af26-fb97e360a6f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8de33fd-eeb1-4f62-a167-102b7ed9f216</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByServicingWarehouse_IsEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>306a1738-4582-458d-816f-c742d7c65f0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1e1f049-6ee0-430e-8f77-902affff9068</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00d3c72f-cee1-447d-b4c8-ce64a52b9e45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f7e7851-59bb-433a-835d-72d45fa37050</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByServicingWarehouse_IsNotEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7df3583d-913c-4833-8300-73ee54833b9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bc8f396-0f50-49d2-b434-31d5a78dff11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50b7da7-f0ac-4ff6-b067-57f042c76a96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61a65f3a-7cc1-4537-b049-4dffb0dfba54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByServicingWarehouse_StartsWith</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08cdeac0-a66a-4334-88a8-6bec5bfb07c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2beceebb-f190-4e87-93d9-b91eb3e4176c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8588e068-40c8-4bff-abf2-b6d2711763e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56396a07-5948-4559-a888-26cd9cbf89c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cf71989-30c3-44f9-89e8-468eb33cc215</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByServicingWarehouse_Contains</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>348a772d-ee3a-4663-a483-574e2690182a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73c7e8bf-15d7-4363-b355-01080db494ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22afe02e-44b9-4d92-8cf2-454c06b17ffe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>344291d3-1114-489e-ba98-0e7a561d6eab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62cfe563-4dd5-4927-b464-8444f8b020e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByServicingWarehouse_DoesNotContain</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03bd9e78-b780-4f3d-8a50-65bf9c1e8907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>091d5761-cadd-4ed5-9859-036c1d9c5dcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4a8a5ce-2e7d-4fcd-ad37-928edd17895f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1cafa11-2344-4ab9-8430-38ea5553da5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify_FilterByServicingWarehouse_EndsWith</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c46db44f-fcda-4543-8515-ee7ed8239328</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b31fcae1-597f-4c70-bb7f-a2caeaae1b5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18139964-7b51-4984-aeba-7fb1969d2c5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e0e0bcf-8bf7-43ed-84c8-a53a52b7e7f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa62cc04-6793-47b7-899b-8deb4a07f847</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByOrderDate_IsEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ceaa7faf-2910-4d71-bda4-4bb96be895eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24b55671-cbaf-48e2-b68e-f4cc20a9d9c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bba32618-c6b8-4258-9a56-6bd0adea147a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByOrderDate_IsAfterOrEqualTo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffecc0cb-2cd2-46f9-8356-60eb6d031413</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb619531-181b-4565-8bd8-efb2867e7f24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d147ad95-d3df-4763-9ab4-2f836c07c2b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b43592b-683c-4878-8d98-1d7ac818193e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb9ee0d3-9a84-4d0a-abb0-edfcb2278c8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByOrderDate_IsAfter</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa665725-78d3-4afd-a2c3-35ec18ba6624</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53760348-1f78-4ac5-ad00-d59906258de4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efb9a6b1-5508-4b3e-a4e8-a1b43a2c3a1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>722250d7-0936-415d-9d16-fadaee085dd8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06366b1e-09f4-4ac2-903a-5477dbd11729</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByOrderDate_Is before or equal to</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbbf5967-9184-446f-a383-53a2ac6b17f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c5cafd3-7674-4f6f-a149-64237414035d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab60f916-4cd8-4998-8a94-968fd4df8c2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50377ce9-686c-446a-ae17-458cdba82ae3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f8ed43c-46ab-4761-987c-39c14584667d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Filter Dispatched Orders/verify-FilterByOrderDate_Is before</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>021e04dc-9fa0-422e-9db0-81013936b431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d87dc19b-cafe-49d8-9b6b-02db28eac4ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8867cc9-b2e5-4295-8e40-1fd81bc989d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaa19967-380f-45fc-a441-62e7c943f4ef</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
