<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_TopMostOrder</name>
   <tag></tag>
   <elementGuidId>45f69d80-228f-4288-8ec0-a2aa45686353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='RepairPoolTransfer']//tr[1]/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='RepairPoolTransfer']//tr[1]/td[6]</value>
   </webElementProperties>
</WebElementEntity>
