<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_WarehouseTo</name>
   <tag></tag>
   <elementGuidId>8d7bebf6-4e2e-468a-84f0-4c1f97daeb48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='frmAddTransfer']/div/table/tbody/tr[4]/td[2]/div/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
