<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DeviceType</name>
   <tag></tag>
   <elementGuidId>e4bec2d3-f35d-47be-a6ef-fc2d5d75a6f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[5]/div/ul/li[contains(.,'${select_devicetype}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[5]/div/ul/li[contains(.,'${select_devicetype}')]</value>
   </webElementProperties>
</WebElementEntity>
