<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grid_outletallocateddemo</name>
   <tag></tag>
   <elementGuidId>1be090aa-a8ac-45c1-a04a-7f147824dd3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DemoDevicesList']/table/tbody/tr[td[text()='${SerialNo}']]</value>
   </webElementProperties>
</WebElementEntity>
