<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_SerialFilterResults</name>
   <tag></tag>
   <elementGuidId>2546ef02-132e-4f6e-81ae-77f6e202e81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DemoDevicesList&quot;]//tr/td[text()='0517011501-001252']</value>
   </webElementProperties>
</WebElementEntity>
