<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cash Payment Plan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>87c764fa-21fd-4096-9c4b-18979fdcca2e</testSuiteGuid>
   <testCaseLink>
      <guid>f50b1d55-6e5c-45ec-a853-a77be59e09d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Products/Payment Plans/Cash Payment Plan/verify_Cash Payment PlanRequiredFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5cf7ec8-0f33-4c44-9b51-9caf8f4993b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1503c4a-00bf-4e55-8105-e968497c4fad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a1e06fe-06f8-49a9-9483-fdcd194f9d73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6880a989-60b9-4490-93d5-54b3f69b6fda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f29805b-7934-4177-b9dc-f8b4aa9fe9de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fbb6676-c3d8-4e59-ad64-d74efd7b8b2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b62bd9e9-09af-4e4a-9586-25285e4de4e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Products/Payment Plans/Cash Payment Plan/verify_Cash Payment Plan Added</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be3bf245-6d76-4625-9141-fffb5144b739</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63fb556f-18bc-4cd7-95ad-1a748cec9af1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f8aec1d-a0b3-42fa-a0bb-64081ce2a5d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dede0a1-285d-4e32-addd-86d727b8ca9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a0b6105-2b84-4b08-81b6-e508c9997bc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01f13eaf-c955-493f-93f6-1df5958123a0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
