<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Demo Devices</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-20T08:48:23</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2e8196d4-a29d-46a5-b55e-96606c4d412c</testSuiteGuid>
   <testCaseLink>
      <guid>e852f1ce-5d4e-490c-add6-4aba78c416e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_CreditsQueued</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3916773f-a668-4eb7-a83a-cf249f5416c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b13dec0-0181-41dc-9708-817bc779a7ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SalesDemoDeviceSerialSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>557db1c8-3fd7-46de-b725-8bb9e503aeba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f758748e-3b87-4e89-ae62-21ce7a019545</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b25a1572-2d3e-4405-9fe2-f26fb8502f15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SalesDemoDeviceAllocatedToSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0536023b-bbfc-4267-b761-25a236d4765a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>581d57ed-052d-475e-a8cb-042fad07356f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d34ab83b-9b70-4555-88c2-64db01a7ab09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_OutletDemoDeviceSerialSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b79e888-0676-4de9-ad88-b3330f6d4a72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0fa9416-7366-453c-bb74-f0215d71d2a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edeee44a-ad5b-48c7-ba1c-dbad6599c4f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_OutletDemoDeviceAllocatedToSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b24d730c-b14a-44fd-86c4-061f741d4864</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5bac7f9-57fd-4ea2-973c-586f7606a57a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e89c4e78-0eb0-4edb-b4f4-a28adec3c35b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_CancelSuspendDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bc82a19-09df-4bf9-bef0-3f33de5c8394</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a053f135-0d77-4cd9-859f-5a04ba40b924</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SuspendDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10f08fab-295f-4de9-9916-fd5e8557e224</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a41f917-8b86-464d-bba4-67d28c06ef68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3adaf776-cbaf-4b59-936e-f2b66cfaece2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_UnSuspendDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>524c1114-3c0b-456f-8701-bfdef9b9ba0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21da81f8-cece-42cb-9b90-a4d462290c56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_ViewSuspendedDevice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfc775aa-f09c-4bbc-b76a-27ba075d0cc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff43df42-2483-431e-9971-a264c8840b40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54cd5a42-985e-4908-851e-5b19dd764d62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/validate_ApproveDemoDeviceCreationRequestBlankSave</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cc7cb23-2df7-4018-bae0-b20f232eb8f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce7b4e9-c41e-415e-ac22-05044b7f46dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03887d39-56d7-4f80-a848-eb4d21b973c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_ApproveDemoDeviceCreationRequest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57e4fdf8-6c25-45b9-9799-f26cde3c9034</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0c3ba6d-2a89-4831-8dc2-bf965de603bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_ConfirmDemoDeviceApproval</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57cd7d48-4052-48e8-9f15-021530195bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f290820c-05a7-437e-83d6-d28cb3c7f1b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>397a7168-04f5-4983-ba81-a0920eb9464e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/validate_IssueDemoDeviceToOutletItemNotFound</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df5e7034-d365-4edf-8c01-5c14bdd33440</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9efc58a3-7572-4acc-8cd6-0d084b27eec1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7181f27e-cd91-4d75-b0fa-85048ff03e8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5d13506-c4ba-470f-8559-28dc1739ae00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b58bf167-e969-4f4a-8dd0-c052e302c57d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_IssueDemoDeviceToOutlet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4dc7455-47ab-4fe4-86c8-5adf35d9e896</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25376997-0ffd-4978-b82d-d651448ae7dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>433d87e1-2102-4497-adb6-2093d5fce150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85622210-4557-4f0a-b292-839620aaf22c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f311412-b0c2-4021-84f8-7771dbe8c01f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/validate_IssueDemoDeviceToSalesRepBlankSave</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>277606e5-120b-47d3-aee5-a1b185df697d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7579af84-7b23-44f0-a81d-5b7d09cb1829</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af915e2a-1b60-4bca-80e3-46c998703264</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62d60d0c-5d55-4667-bb3b-802d30f9115c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_IssueDemoDeviceToSalesRep</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>547db9b1-94f4-419b-97db-35e6f743df77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76ddaa00-48ee-43c0-82a4-4155a4fb7ef3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45ce6c43-59fb-44c4-89ef-916f082a13ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea42f5a1-edbe-46dd-9833-98da662b0c37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_DemoDeviceAllocationToOutlet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>687bf82e-31fc-4f0d-a1a1-076eed05bf1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a8d095f-a81c-4a13-9417-03c39593442d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_DemoAllocationToSalesRep</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ad4db6b-611d-4115-a96f-92407036adf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df2f57ec-811e-48d8-b96d-8139443f8371</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_UnsuspendedSalesRepDemoDevice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>287e4350-d289-4706-9b7e-bb53206c6757</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>904292a0-6721-41c1-8e3e-6f1cf8bf86be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SalesRepSuspendDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d59ba52-dfe6-4079-9819-27bb363c30fa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
