<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes all the operaions done on demo devices</description>
   <name>Demo devices</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d51c15e9-a79f-4523-807b-f00a4ba4444a</testSuiteGuid>
   <testCaseLink>
      <guid>9084980c-060a-43a2-90fa-9c4ca3ac4fa3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/validate_ApproveDemoDeviceCreationRequest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cc7cb23-2df7-4018-bae0-b20f232eb8f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ce7b4e9-c41e-415e-ac22-05044b7f46dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b27dcb9-ec9d-4df9-a4bc-1cd3a1d1ab28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_ApproveDemoDeviceCreationRequest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57e4fdf8-6c25-45b9-9799-f26cde3c9034</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d67d75b9-8fae-4622-ba92-231b1ad25e1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_DemoDeviceApproval</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57cd7d48-4052-48e8-9f15-021530195bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f290820c-05a7-437e-83d6-d28cb3c7f1b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>111db7c4-c589-4406-8581-5ad01fa61615</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_ViewAllocatedDevice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3c09d76-b05e-4d6f-91db-7d239f6feb1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c4c9b37-76cd-41fc-b6d0-7b120d5fa21b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/validate_IssueDemoDeviceToSalesRep</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>277606e5-120b-47d3-aee5-a1b185df697d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7579af84-7b23-44f0-a81d-5b7d09cb1829</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af915e2a-1b60-4bca-80e3-46c998703264</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5966715-6df1-41f2-a396-4c974571eded</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_IssueDemoDeviceToSalesRep</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>547db9b1-94f4-419b-97db-35e6f743df77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76ddaa00-48ee-43c0-82a4-4155a4fb7ef3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45ce6c43-59fb-44c4-89ef-916f082a13ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40a99dc4-accb-40ab-8e68-90295a3d6c20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/validate_IssueWrongSerialNumber</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>173e5ee2-b81b-4e1a-8c9e-dd8ca99887ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2eb519c-3b73-4aad-a854-4509cad9ce27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e36b92-d533-4767-bc79-fa81759e32af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>393d6f11-223f-453b-bf9c-6f93aeb203fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da6355bf-5125-4f8c-92d0-6c7637f59900</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81494b5d-81fc-42be-8bbe-837ce9df443c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_AuditlogSuspend-UnsuspendOutletDemoDevice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>318c5904-3850-4738-928c-e27adaeb66eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_AuditlogSuspend-UnsuspendSalesRepDemoDevice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d9b7950f-1cf0-4853-af37-1f982e2841d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_DemoAllocationToSalesRep</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ad4db6b-611d-4115-a96f-92407036adf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8759a582-d559-4733-a91d-9add892ec7aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/validate_IssueDemoDeviceToOutlet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df5e7034-d365-4edf-8c01-5c14bdd33440</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9efc58a3-7572-4acc-8cd6-0d084b27eec1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7181f27e-cd91-4d75-b0fa-85048ff03e8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5d13506-c4ba-470f-8559-28dc1739ae00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8684a710-db95-40cc-b64e-04a6e0ffd7de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_IssueDemoDeviceToOutlet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4dc7455-47ab-4fe4-86c8-5adf35d9e896</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25376997-0ffd-4978-b82d-d651448ae7dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>433d87e1-2102-4497-adb6-2093d5fce150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85622210-4557-4f0a-b292-839620aaf22c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b671027-0972-4f38-a065-fbf7513372b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_DemoDeviceAllocationToOutlet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>687bf82e-31fc-4f0d-a1a1-076eed05bf1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ea8b300-397f-4c88-981f-a6aa514c13bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_OutletDemoDeviceAllocatedToSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b24d730c-b14a-44fd-86c4-061f741d4864</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5bac7f9-57fd-4ea2-973c-586f7606a57a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1b07c7d-0c94-424d-8cde-08a7a494e395</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_OutletDemoDeviceSerialSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b79e888-0676-4de9-ad88-b3330f6d4a72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0fa9416-7366-453c-bb74-f0215d71d2a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7acbc456-ff29-41fe-b6f6-40d13d7bbccd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SalesDemoDeviceAllocatedToSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0536023b-bbfc-4267-b761-25a236d4765a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>581d57ed-052d-475e-a8cb-042fad07356f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f557de85-df01-4f3f-b691-6460eed73d4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SalesDemoDeviceSerialSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>557db1c8-3fd7-46de-b725-8bb9e503aeba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f758748e-3b87-4e89-ae62-21ce7a019545</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9bd3274-0a5e-4ae4-94dc-0a65c038ba1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SuspendDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10f08fab-295f-4de9-9916-fd5e8557e224</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a41f917-8b86-464d-bba4-67d28c06ef68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb8b1e22-6f61-4fec-b36d-59ef1763feb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_ViewSuspendedDevice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfc775aa-f09c-4bbc-b76a-27ba075d0cc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff43df42-2483-431e-9971-a264c8840b40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00fd4f70-dcbb-4e3a-85e8-37f5c526ad23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_SuspendSalesRepDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d59ba52-dfe6-4079-9819-27bb363c30fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6aabbe7e-8bcb-4f5c-a524-6bc391bc410c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_CancelSuspendDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bc82a19-09df-4bf9-bef0-3f33de5c8394</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>823d97b2-b39d-48c4-873d-b716230a5955</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_UnSuspendDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>524c1114-3c0b-456f-8701-bfdef9b9ba0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0754ae2-8fca-466b-b27f-386906d86abc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_UnsuspendedSalesRepDemoDevice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>287e4350-d289-4706-9b7e-bb53206c6757</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8d7440d-c7c8-4e1c-90c6-81492c543145</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Demo Devices/verify_CreditsQueued</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3916773f-a668-4eb7-a83a-cf249f5416c3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
