<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test Suite for Customer Payments Test Cases</description>
   <name>Customer Payments</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-08T14:10:20</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e60c1404-6775-48a9-8785-6dd5e21d82a7</testSuiteGuid>
   <testCaseLink>
      <guid>35c5e234-80d6-41a3-9719-e02ccdd162a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Customer Payments/verify_Customer Payment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6024dd6-cf55-4095-a04a-66505c2b2692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>821d9392-8119-42b4-b1fb-0f21005337c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056f2335-96ca-41d3-9ffe-e2c4678edb82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bafc285f-cc27-47a7-8815-2c4980340d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9762f7f5-9287-4118-8e20-e73139e05b46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Customer Payment Notitfication (SMS)/verify_Sms sent on correct amount deposited</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85bb640e-291e-4c6b-b637-a7f626c12694</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cba0f0c-a789-42cf-a19e-e032cfd102f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837ea428-a633-4764-950c-5a29b18a4e27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ed97df-9eef-47cd-bd1d-24048598cb98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b0594d-d7b8-43e6-8ab5-dc701843d8e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0972a4c-ade9-4a60-945c-e6b2bf488d24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payments/Search For Payments/Search For Payment Using a Receipt Number</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4245c0a-e8cf-4c6e-8a35-b9cd38e0121d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
