<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Receipt of Consignment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-02-23T07:42:59</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e0d90c30-ca23-471e-b517-c00cf935b290</testSuiteGuid>
   <testCaseLink>
      <guid>f72d74c9-10e2-46c1-9342-eba899bb8dfb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Shipping Date Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c328ac-8348-47b3-bb75-fbfe6143a60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03bed94b-834f-4a14-8dd5-e3696382aa3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67999170-f7c0-42f5-a4ba-f50dfc368a1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18779ded-09d0-4ec6-a4f1-6032c9abd08a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>300b01fe-2f05-4b8b-945f-9c9bc6779fee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>653db032-af61-4586-a61a-c85428a845f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25efe9a5-78e7-4228-8821-88dc28c90401</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Duplicate Consignment No</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>409a6bf5-9ca6-4faf-a2e9-9a10320b6fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c6adb4-2f01-47c6-8bce-eca5f9c390e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d6a5880-2f2f-48f0-bebe-4f6ddf192fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ea8e21-70d5-4339-b2e4-95aea63234ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30f23dd3-fe6c-4780-8429-ba27a0374635</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9084848-e228-46db-a186-64d0a9057865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a590315-ec35-4658-906f-61b423cec05d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>067ca1a5-b9d8-4ac9-9656-d0223e165e98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_csv File Extension Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec7676a-5f9f-44e0-ac04-7dcf8ce21e5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66a1a719-1bd6-4eeb-955d-a805a86db58c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>009f6356-dafe-4bf6-9912-f0c0655bbe6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a7595eb-d966-47a9-afe4-94f82e38f9df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d65c64-3bfc-4425-9beb-c7dcadba0d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f805360c-5f02-4f81-92bb-5068e7c4f184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fb3134b-ba44-48e2-86c7-f8c2ac8c9d2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inventory Module/Receive Consignment/verify_Large Consignment Upload</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c994c470-852c-4635-aba4-1e1a31994d30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d60a9704-d7a4-4bf4-b847-46f411d7826f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43359052-4f15-40f5-818a-543436e457fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d64f9854-3303-4e5b-ab9a-be4c2aa8caac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2960e462-cc80-4db2-b9d9-96e1b6b6b17c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e624d5d8-7e2c-4b34-9e5e-a188e38200d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793d8fb9-f47d-461c-a9be-da98aeae2fc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aca1ac4-eaff-4b6a-9fb2-f9bfae11f361</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>801915a2-ac34-41c5-b3f7-2681a1e8362e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inventory Module/Receive Consignment/verify_Receipt of Large Consignment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f2f3f5d-ee46-4e80-8652-b377e185a095</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cea46a56-e2ce-48be-99ef-81553d6da353</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b5d708c-e0ee-450f-9349-896b11ba1e03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d094372b-85de-4673-9b4e-6249f73d5f22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e7bc004-6e36-484b-a666-069cce926aea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7acd30e1-414d-4166-8509-911fe745b4ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>487f8ac1-d7b7-477f-8bd9-1e48d2a2efdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>601c6155-3fec-4e4c-b8c3-705e7847e8d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7e2a2d8-f06f-4dae-9c8e-f42623c11365</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a53a59d3-01cf-4d95-8f00-17bdd143fa2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e71993e-4a79-4269-956e-e2011ff4aa15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c8f7c59-0032-4d48-a24e-df79b063f753</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95827ca7-fb92-4de2-b3dc-21357254197f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8489c781-93d0-48e6-b86b-f73cbf4ea542</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Data Duplicates in the Database</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86882527-4bd9-41ed-a745-11839f4732ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb59f05d-3646-4a3c-bdfd-3759699dd0cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5a6dad6-be48-4522-b8d8-a38138596a38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fee24d8b-61bf-40df-82f0-635dddd037a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c519eef-262d-4a6e-a15f-db43c7995411</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96d8ba1c-4d07-4500-bc7c-c5cb1fc9abe9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
