<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_LoanStatus</name>
   <tag></tag>
   <elementGuidId>fdf76b36-7926-40cb-b37f-d73a69596817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='div-account-info']//span[text()='${loan_Status}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='div-account-info']//span[text()='${loan_Status}']</value>
   </webElementProperties>
</WebElementEntity>
