<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_AmountPaid</name>
   <tag></tag>
   <elementGuidId>160225b2-56cf-41ea-9dbb-cbf4b329d60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;div-last-payment-info&quot;]//div[text()='${total_Price}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;div-last-payment-info&quot;]//div[text()='${total_Price}']</value>
   </webElementProperties>
</WebElementEntity>
