<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_OutletId</name>
   <tag></tag>
   <elementGuidId>d8db057f-f434-4bbb-a09d-f55bd8d8002e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='346fe279-6c28-e311-aa25-000c29d93d1f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='346fe279-6c28-e311-aa25-000c29d93d1f']</value>
   </webElementProperties>
</WebElementEntity>
