<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_CCR</name>
   <tag></tag>
   <elementGuidId>8f04fe59-e8f1-4923-a8e0-eeba358d104f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name='MultiChoice[9e2e74eb-9688-e711-a9a8-000d3a26b7ad]']</value>
   </webElementProperties>
</WebElementEntity>
