<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_States</name>
   <tag></tag>
   <elementGuidId>e7da9c05-cf5c-4dc0-a4c5-d235cb4209d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;OutboundStates&quot;]/table/tbody/tr[1]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
