<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Warehouse operations</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4d16db1f-7ec4-47c3-80ad-bd472d02df63</testSuiteGuid>
   <testCaseLink>
      <guid>579f0e1f-a3ad-4561-9db4-93a62009c9e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/verify_View Return Tickets</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54340856-6976-410f-8b61-94024cfd0a9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d520bc47-ecf0-4ce7-84c9-83ca03ae8257</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b44dbbab-6ab2-48be-916e-01fbc67f5c7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/validate_receive dealer returned device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2fd0a36-9c71-491f-9e38-1485a5f3b15d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fafe16ee-de13-4a22-8350-317c61dfa9bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b026346-185d-4844-9f12-b9b3a19ea56e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d1d804a-9122-4703-90a6-4bf18c09aec3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b221cdf5-4391-4dd2-87e9-fcbe058027bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/verify_Receive Dealer returned device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b13a9f63-deaf-4097-ab17-bfdbdbcded16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>689fa54a-d3d8-43d1-bbe6-0c12c0eeec74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bee99aa-e8e5-4ec0-8c59-e8c7b6ad6025</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d93927ec-8230-43a0-a3b9-53d8c9a2a040</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>340b7a30-abd3-4d92-a287-fd6e0052de0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/validate_Receive customer returned device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>235eaab8-aee2-4bc8-a893-d4a26ce38424</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f47f11aa-dfaf-46c4-95bc-2ca6d5fc9726</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e84de61-ba50-4c04-bcb2-da37e63b6e04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8a9f974-aaf3-4236-800d-c9ec86774032</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/verify_Receive customer returned devices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6cad9ca-d561-45f9-9bc4-09a6e407912d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3f4bbb9-5b2a-48d2-abab-8a14d54ef186</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ee4ed9c-cd95-4564-9fa6-47f8dd66d885</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa64169c-ca19-481d-ac61-74f7c22a23c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/validate_ValidSerial_PickNewDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f0030db-3301-4cbd-820e-a4f9cae1f8d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a96096-aa90-4f59-86f1-49bdf338fb0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0822170a-25d4-4954-8e92-575639b4cd48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c68581a-112b-49e7-b77c-e914e5d0e4f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67204054-4455-40cd-b7d9-838eaf3944c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b40158c9-43f4-4183-a3d1-daf61b37fafa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/validate_AtleastOneDemoDevice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae86efe1-a36e-4a44-8e98-9111965ade23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a817cd1c-db22-4be1-9902-2e778c23b019</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30afc377-a564-4435-8ba5-30dc2ff9eba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b7e03ce-f000-460e-9f9b-89ef0021e1e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>038f16da-4515-40ab-89f8-2874035a90b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12b882f5-23ae-424f-a439-be04366d8a1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/WareHouse Operations/verify_PickNewDemoDevices</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27de75b5-a924-4533-b240-1b5b0e9e02a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6df8887a-ec6f-43ce-b0ab-b8199887b072</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8025260-f2b7-445e-8a40-e7f5dca066b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2043e814-f65d-475a-a2ca-65a2bf06bef5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa03d6a8-dda3-4a1f-8169-d7cb38ccb033</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
