<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>statessent_Element</name>
   <tag></tag>
   <elementGuidId>d84c41d1-b664-48c0-9c5e-77fe96c6f176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='OutboundStates']/table/tbody/tr[1]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
