<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_SelectSalesAreaCountry</name>
   <tag></tag>
   <elementGuidId>dd413961-27da-418a-80ed-204ed716eef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;divBodyForm&quot;]/form/div[contains(normalize-space(),'Select')]//div/span/span</value>
   </webElementProperties>
</WebElementEntity>
