<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_SelectCountry</name>
   <tag></tag>
   <elementGuidId>96e1ed2e-5e88-4319-ba09-4129e8802983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/ul/li[text()='${country}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/ul/li[text()='${country}']</value>
   </webElementProperties>
</WebElementEntity>
