<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Uploading various manifest types</description>
   <name>Manifest Upload</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f3088c67-c571-4676-9f0a-b40009881b61</testSuiteGuid>
   <testCaseLink>
      <guid>c04a9672-2db6-40e4-9791-02873e8412a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_consignment Status</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12e4d950-1d4f-4fda-9d81-43fa35c49515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07022687-a209-4535-979e-bd88bf60a5ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aeba807-06c1-4506-bddc-9ab1c47b010f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d149d14b-5eb8-4da1-87bb-06c67c68e47e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0588f761-fdb3-4f40-84b6-fd301f5c0f27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65f46bd5-f114-4656-98f9-bd4a9045b021</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5f396f2-a64e-4622-afa5-0cafb50bd7ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb7f8c75-92c9-4e27-a06e-9711fe8b96ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5bd5c53-0374-4773-91cf-f9f383657090</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64cb7842-5f4f-4040-8669-fda68bd4e289</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_csv File Extension Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ec7676a-5f9f-44e0-ac04-7dcf8ce21e5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66a1a719-1bd6-4eeb-955d-a805a86db58c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>009f6356-dafe-4bf6-9912-f0c0655bbe6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a7595eb-d966-47a9-afe4-94f82e38f9df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d65c64-3bfc-4425-9beb-c7dcadba0d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f805360c-5f02-4f81-92bb-5068e7c4f184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>551c9458-1ea2-4f1d-afa5-e3b9ef0f9251</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Data Duplicates in the Database</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86882527-4bd9-41ed-a745-11839f4732ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb59f05d-3646-4a3c-bdfd-3759699dd0cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5a6dad6-be48-4522-b8d8-a38138596a38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fee24d8b-61bf-40df-82f0-635dddd037a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c519eef-262d-4a6e-a15f-db43c7995411</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96d8ba1c-4d07-4500-bc7c-c5cb1fc9abe9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20b9da15-04f9-477f-948d-26ae72c520f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Duplicate Consignment No</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>409a6bf5-9ca6-4faf-a2e9-9a10320b6fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c6adb4-2f01-47c6-8bce-eca5f9c390e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d6a5880-2f2f-48f0-bebe-4f6ddf192fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40ea8e21-70d5-4339-b2e4-95aea63234ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30f23dd3-fe6c-4780-8429-ba27a0374635</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9084848-e228-46db-a186-64d0a9057865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a590315-ec35-4658-906f-61b423cec05d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e67cfce-9d04-40f7-a8ac-dd0b7eb2a0c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_EnterLoanDrawRequired</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ed8a83f-ba87-4463-b972-6147db83703a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fdaa753-057e-41d8-9380-a06f44c53258</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae8e4d15-62b4-41ae-9382-4a35f91bc55d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f91d004-84b9-4cd8-a645-5884fd066807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ac49f8-2494-4739-9101-1964295c3188</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4928f2e-2fe7-4380-b32c-7e03b8d97150</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Shipping Date Required</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c328ac-8348-47b3-bb75-fbfe6143a60f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03bed94b-834f-4a14-8dd5-e3696382aa3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67999170-f7c0-42f5-a4ba-f50dfc368a1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18779ded-09d0-4ec6-a4f1-6032c9abd08a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>300b01fe-2f05-4b8b-945f-9c9bc6779fee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>653db032-af61-4586-a61a-c85428a845f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5aa9d569-7cb8-4fed-895c-60c0f7f2b24a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/validate_Wrong Manifest type Upload</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e419c42-7a44-4274-9235-1b1921726e0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be56cb9f-3485-4f1d-a313-c78da628bd9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a1560ce-a99c-464b-b5fd-03256b59c468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdc06ad1-611f-40d7-9ec4-7d58e8a9aa60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7210fdb-1c2d-443a-82d8-71886453ae22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d19671f-1920-4d48-8289-559832d2633c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>486761c8-dc77-4083-8670-439daeb42f43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ef66a6f-d875-4dd1-98db-53ca0ff8f99e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>638474cc-4bbf-4d38-a090-a66234af62c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9399c2d-1865-43c0-864a-c49606ff6777</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5e95c06-7412-425c-a840-c58a890bbca8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Metered Uploaded Items Lists</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16cc982c-d96d-4324-8f29-bb8eb8691c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfe1dccc-3757-4240-89c4-db78c895a1f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73efbbc3-f600-45a4-86b2-bee89d656b9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12bbcfc9-b23a-4c86-88a3-79530132d08b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1abcf00c-d735-48ce-a812-b4fcc19723a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88719649-d52a-495e-9e43-f0045754c839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d127f10c-93eb-4314-b26e-7585a7a7ff08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5264e304-9e49-4bd6-999b-754ce0724afb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80353c78-7062-4632-b47f-d01932749a55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Uploading Hammerkop Manifest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7eb48130-a450-4873-8372-8db7edfae04c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>244104dd-93bd-4e9c-a6b1-62adf2dff9ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>913d7346-5eda-49fb-81af-1134507e83a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d002bb6e-0d92-4e61-87e7-b589ef831905</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06bb765d-8625-4b35-b720-a7462ff3c104</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Uploading Kingfisher Item Manifest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c270069-d9bf-449b-9bdb-fc17602df126</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8f9ef3e-55d7-468f-9fb9-45235c5201e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fd17f2a-e84c-4d8b-86dc-32c053359646</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b3901b-9bbf-4cd4-8d1d-bb618db5e1ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fceadc92-5b9e-4116-8000-20f5a05a3d63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0903e21e-b1dc-4219-92fb-05778518a4d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d994605-7927-448f-87a0-3791547537ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d1c873e-05ef-4eff-b045-fbd999a39581</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9cf353-e27e-4550-a799-67a7594c3984</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ada345e8-2405-4bb5-a9dc-38b5be1a4570</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Manifest Upload/verify_Uploading metered Item Manifest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4487e167-1b1a-4595-9663-8a3d37b7ef52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b07fcc-6e1a-4519-a7c2-bbb43da8b2fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde994af-3f3d-49f6-80d8-b5da681ae173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ac3c015-5b94-4d82-9ac6-07b9a1670dcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7941fd5-3852-4df8-8b05-733aa5351c53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fecada69-5f9b-46d7-a22a-6260c63a9de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a4b878-9c74-4303-be4a-231453302b18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3a03ae6-101c-4f40-bff0-02c5664663d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d85c58b-ac96-4604-8a6b-029d648925d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a91714d2-8c4f-4e64-880a-1762e4a24a27</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
