<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Approve</name>
   <tag></tag>
   <elementGuidId>5f17301f-821c-4cd0-b5ce-ea58eafcf24d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='productcacellationgrid']/table/tbody/tr[td[text()='${customerAccount}']]/td/a[text()=&quot;approve&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='productcacellationgrid']/table/tbody/tr[td[text()='${customerAccount}']]/td/a[text()=&quot;approve&quot;]</value>
   </webElementProperties>
</WebElementEntity>
