<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes Operations done on D10g devices</description>
   <name>D10g</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e312df24-773e-403b-99e5-98be892d101c</testSuiteGuid>
   <testCaseLink>
      <guid>5df8af0a-c611-422f-b450-c58927c7e072</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D10g/verify_Send credit D10g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c2a5480-4cc8-45b8-bc54-4fde1aeb0702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e05b0cf3-b10c-45e7-9e6a-b5cd10a0bdff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0811ba39-026c-45da-a964-2e219460eaf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2dfab7a9-7ff5-47c5-958d-8b6342694482</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D10g/verify_view credits sent History D10g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>726b4d60-4279-4ffb-95a9-f9e5d2224e55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>250ced16-cd46-4cb1-b5d8-e96d0f7c0e9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>159a4d02-55e5-48f8-91b9-61610a11238e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d621130-8efd-4ff0-a65a-b424ca1461dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D10g/verify_manual state sent D10g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>881327e7-68d3-43f8-b888-55515df2f6e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba654c42-73df-44da-a700-5a675a00dd97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76aab510-27c3-44af-8096-fb508c33ff2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4312d301-8503-4d33-b999-c1bfdb554eb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a38b3276-b12d-47e8-b1e0-19be2a7104ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78fa085-c893-437b-928e-68abbe7e6755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd37d538-89aa-4cbd-8b5a-01fc88ea0a41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d886e479-f727-43ba-af7f-b37104c96f7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D10g/verify_Send state D10g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b514895-4d89-4e87-ba74-594027d2dd6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d6c6d9a-f4e8-408c-9b23-823226684a17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a01a786c-43d8-4aa0-adde-64780a3070f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0d4ad82-ed45-4965-9f60-51395073e3ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Metering/D10g/verify_View states sent History D10g</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb327c14-27c9-4efc-9a6c-19feefa6fa18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5222fbb-221e-4944-a2fb-c0595547f959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7ae5764-5065-4fed-9e47-8508896fc099</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
