<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_OutletProductDetails</name>
   <tag></tag>
   <elementGuidId>5d9847aa-70bf-4aea-b857-c063225ac24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyMain']/div[contains(normalize-space(),'${outletproductname}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/div[contains(normalize-space(),'${outletproductname}')]</value>
   </webElementProperties>
</WebElementEntity>
