<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_BlankValidation</name>
   <tag></tag>
   <elementGuidId>0f924803-4aa3-41e5-b1b6-46983afa396e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyMain']/form/div/div/div/ul[contains(normalize-space(),'ss')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/div/div/div/ul[contains(normalize-space(),'ss')]</value>
   </webElementProperties>
</WebElementEntity>
