<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language</name>
   <tag></tag>
   <elementGuidId>6e4e62b0-1c35-43eb-94e9-3687bf89d056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body//div/ul/li[text()='${Language}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body//div/ul/li[text()='${Language}']</value>
   </webElementProperties>
</WebElementEntity>
