<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IDType</name>
   <tag></tag>
   <elementGuidId>91ee3dff-fe92-41f8-8852-3ffa81d2bd42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body//div/ul/li[text()='${IDType}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body//div/ul/li[text()='${IDType}']</value>
   </webElementProperties>
</WebElementEntity>
