<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SalesArea</name>
   <tag></tag>
   <elementGuidId>b3cad7a1-f1d7-4e3f-b7e2-1a74bd8cc0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body//div/ul/li[text()='${SalesArea}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body//div/ul/li[text()='${SalesArea}']</value>
   </webElementProperties>
</WebElementEntity>
