<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_DealershipTypeChanged</name>
   <tag></tag>
   <elementGuidId>ea376976-a6ae-4d35-b307-fd4de655992d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='divBodyForm']/fieldset[1]//div[contains(.,'${confirm_dealershipchanged}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyForm']/fieldset[1]//div[contains(.,'${confirm_dealershipchanged}')]</value>
   </webElementProperties>
</WebElementEntity>
