<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ProductType</name>
   <tag></tag>
   <elementGuidId>a2780dbf-bdc4-42e2-8b40-fe6a58a8ec43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*//ul/li[text()='${producttype}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*//ul/li[text()='${producttype}']</value>
   </webElementProperties>
</WebElementEntity>
