<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Operations</name>
   <tag></tag>
   <elementGuidId>6c6efc52-bf95-4316-be62-c8801170274d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*//tr[td[contains(normalize-space(),'${code}')]]//td/a[text()='Operations']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*//tr[td[contains(normalize-space(),'${code}')]]//td/a[text()='Operations']</value>
   </webElementProperties>
</WebElementEntity>
