<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_details</name>
   <tag></tag>
   <elementGuidId>7b0a3124-72d7-43a7-92f0-c6d483aaacb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*//tr[td[contains(normalize-space(),'${code}')]]//td/a[text()='Details']</value>
   </webElementProperties>
</WebElementEntity>
