<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_OutletProductType</name>
   <tag></tag>
   <elementGuidId>e8ca8d79-66dc-4e63-9ee9-8b64c23189e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='ProductTypesToAdd']/option[text()='${outletproducttype}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='ProductTypesToAdd']/option[text()='${outletproducttype}']</value>
   </webElementProperties>
</WebElementEntity>
