<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executes all the dealer operations i.e. adding dealers and managing them.</description>
   <name>Dealer Operaions</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9267f86e-81f6-4f34-8d5c-c1c20ccda01f</testSuiteGuid>
   <testCaseLink>
      <guid>16dd6c2d-6c99-49e5-ae9c-f9cf43b03f65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Dealer/validate_AddDealerBlankSave</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a88a1fae-3942-4a68-acb3-6e677611bfbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f16b1b89-6d5a-45d0-a5ca-0d1dbac44a1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Dealer/verify_AddDealer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c609a3-ba95-4bdc-9c7b-07886f3f255b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a6849b8-f0e2-465a-96ca-6f766d9fae2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47c821f5-a037-4a39-89ef-9728f9ef7f53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23ded732-5980-44d7-a44f-be3bf3f609e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd737557-cfa2-402f-b2f5-ec5f4174ce09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71a83c8d-3f01-46bb-b853-de7efb0f3f51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da463af7-7efd-424d-b584-517970f70dec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c680ff8-d3ac-444f-9db8-d8e7c2989cdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed3cbd8d-ee10-4cfd-af10-1dfa1404e143</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f88e1968-d6d2-4778-bb05-1a4b53e710ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa08c811-de58-4199-810a-a07d41277611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dddc5bb5-6cd2-48a3-9dc9-d82a0e1e616a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af250087-a0b3-47ed-b1eb-589397814225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d25fd8-f20a-4901-838f-d0574bddfaed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ea15b34-54f2-4943-a54d-b527a4597630</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8edd859f-7374-4335-ae67-3b00073a2325</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f8e486d-a0c5-48a9-b586-368efbc065bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66a87d3a-375d-427c-a3ae-8dc1370f8d87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e66065b-5d52-45ba-aabb-3cc780f3ce55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f3962cd-e88f-452a-b9a7-f38950baf573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a4a017b-60e0-4988-90ae-22d63e5bdd17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b577d6-d11f-46a9-814d-023d3571892e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb574fb7-ed5f-48b9-8ac2-9d5d45ebb049</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39da3d14-d942-4739-a176-52158e46a9f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Dealer/verify_EditDealerDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59d6ca81-ad36-4213-b097-7fbc2833442f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b952a95a-451c-4f92-8bd1-a66dcf4973be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>999d1a25-e28c-4c17-abd7-bbcba3eb8d20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86dee9c5-6178-4b9b-bb35-c0efa0a96e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Dealer/verify_ViewDealerDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24913243-b054-487d-bf65-6ed3ccf02948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eee2156-c191-44f0-a623-d3ffea588a50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aebd24ee-25d8-4671-bb04-2dce5cd6b976</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Dealer/verify_ListDealer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec9d316e-4a56-401c-8348-69df16725ef5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3403eca3-8f10-4931-a27e-57054954cbec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfaf7595-cb47-4697-8ff3-9af7c892c0af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Dealer Manager/validate_AddDealerManagerRequiredFields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26545324-6811-44ed-8eef-f36be27801ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca55ac85-6fef-45be-9f44-eb391e0c71f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Dealer Manager/verify_AddDealerManager</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c99e7c4-6fc1-437c-8528-93843ec8ef50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f95ddef-37d3-4e38-b71f-97808399c407</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a236e088-9a30-4346-b84a-82d100e4381f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f9a488-4868-47a6-b4fa-422cd67abdf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6c6b8ee-8f46-4d22-98d0-ae8328399820</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eab78c9a-be4e-4072-9d5a-f6146f6b128b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69238a3c-e839-4e66-b9bd-98f55fd87984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02424bdf-2fd5-4969-b519-73dc514024aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe82bce3-635b-4e74-9e5e-01ac769c3f9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cb3cb5b-10b6-495e-9b82-72473309b8f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0babeb27-f06d-481d-aa5f-e1f712cbd8c9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
