<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Purchase Request</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>dfcb74a4-4920-4756-82aa-443d107791eb</testSuiteGuid>
   <testCaseLink>
      <guid>bdc85dfd-a07f-4c08-8ec4-797ee08c154f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Make Purchase Request/validate_required fields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab32d066-01a3-4677-8b75-7e1160b53029</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f896faa0-09f3-423d-8c6e-202a1ba8db3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1867e395-3b7a-4380-b082-ee1a0aebc78d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acfd8c52-9556-46a4-9d82-e0724c5934c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3df8c4c1-197b-4d2c-94e5-69ed843a7799</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8eca9e6-f377-4ef2-b80a-9805137e925d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>466a9571-51e4-4d1d-8b50-23f3fd31ccaa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Make Purchase Request/verify_Make Purchase Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c48564d-6887-41a4-b434-426d7396f58b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e787e5a-6b73-483c-8974-d13bd54537ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>825ad429-55f7-4ce5-9cec-b7b0b45a43bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295c4d3f-459f-40c4-a793-9e47b4300233</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6843a631-80f3-49bd-95b0-03a14220fc33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e12bee1-5372-498c-9867-ae04a2d1f648</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dealers Module/Approve Purchase Requests/verify_Purchase Request Approval</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9229e606-9fa1-4294-aff5-518b7432f10f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
