<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_FirstSelect</name>
   <tag></tag>
   <elementGuidId>3e682dc1-0ff7-4257-90a2-e75074502112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='DispatchedOrders']/div[2]/div/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DispatchedOrders']/div[2]/div/select[1]</value>
   </webElementProperties>
</WebElementEntity>
