<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_SecondSelect</name>
   <tag></tag>
   <elementGuidId>bcd38302-5e71-466f-80f1-d84ca6497561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DispatchedOrders&quot;]/div[2]/div/select[2]</value>
   </webElementProperties>
</WebElementEntity>
