<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_OrderNumberSelect</name>
   <tag></tag>
   <elementGuidId>9c58924f-ab38-4fda-9e96-95d3a618f0d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='DispatchedOrders']/div[2]/div/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DispatchedOrders']/div[2]/div/select[1]</value>
   </webElementProperties>
</WebElementEntity>
