<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_OrderDate</name>
   <tag></tag>
   <elementGuidId>d54bbc45-0a88-4afb-89b6-79d3495bf08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[8]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[8]/div/span</value>
   </webElementProperties>
</WebElementEntity>
