<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_ServicingWarehouse</name>
   <tag></tag>
   <elementGuidId>eed2181b-1a12-4a72-93aa-0ab30c3d145e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[7]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[7]/div/span</value>
   </webElementProperties>
</WebElementEntity>
