<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_OrderingOutlet</name>
   <tag></tag>
   <elementGuidId>0b8365b7-23c0-4e49-b34e-b6d161258faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[3]/div/span</value>
   </webElementProperties>
</WebElementEntity>
