<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateDispatchedFirst</name>
   <tag></tag>
   <elementGuidId>f0685bde-3ee6-4e7b-9a21-5f0f77b9da7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DispatchedOrdersEADateDispatchedfirst</value>
   </webElementProperties>
</WebElementEntity>
