<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DispatchedOrdersEAOrderDatefirst</name>
   <tag></tag>
   <elementGuidId>b040338e-3b38-4248-91e1-c708214de1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DispatchedOrdersEAOrderDatefirst']</value>
   </webElementProperties>
</WebElementEntity>
