<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrderNumber</name>
   <tag></tag>
   <elementGuidId>fb9f0f8a-380c-440f-820a-fc808064ca99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='DispatchedOrders']/div[2]/div/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DispatchedOrders']/div[2]/div/input[1]</value>
   </webElementProperties>
</WebElementEntity>
