<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_OrderNumber</name>
   <tag></tag>
   <elementGuidId>d1673979-dcd6-4e3e-bb2b-2c308af492e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='DispatchedOrders']//td[text()='${order_Number}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DispatchedOrders']//td[text()='${order_Number}']</value>
   </webElementProperties>
</WebElementEntity>
