<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_DateDispatched</name>
   <tag></tag>
   <elementGuidId>f90358d8-6d13-4291-b1cf-11e0ee270232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='DispatchedOrders']//td[text()='${filter_Results}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DispatchedOrders']//td[text()='${filter_Results}']</value>
   </webElementProperties>
</WebElementEntity>
