<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_TrasnfersIn</name>
   <tag></tag>
   <elementGuidId>112e4686-aa48-468a-8569-524ee64c10ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@href=&quot;/Inventory/InventoryTransfer/InventoryTransfersIn/${transfers_in}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
