<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Outlet</name>
   <tag></tag>
   <elementGuidId>778d9584-700e-4b87-9f29-5b135a3bf82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='DealersOutletList']/table/tbody/tr/td[text()='${outletName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='DealersOutletList']/table/tbody/tr/td[text()='${outletName}']</value>
   </webElementProperties>
</WebElementEntity>
