<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Warehouse</name>
   <tag></tag>
   <elementGuidId>682c26e4-a1e6-45dd-b564-90e56f442eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*/div/div/ul//li[contains(text(),'${warehousename}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*/div/div/ul//li[contains(text(),'${warehousename}')]</value>
   </webElementProperties>
</WebElementEntity>
