<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Executing warehouse transfer from one warehouse to another</description>
   <name>Warehouse Transfers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0904c42f-3ea4-46a9-8009-268b0e9e05dd</testSuiteGuid>
   <testCaseLink>
      <guid>5f3edf3d-dc7e-4d4d-9bc5-0ac375e862fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Warehouse Transfers/verify_Warehouse transfers out</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b059db3-d0d2-438f-917f-c384812e02b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0253aad0-05dd-4b1e-a144-63bf5842ac26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1d8ada1-5001-4d5b-87e9-9482ed78b124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c183efa-9757-4678-8da9-c1994ab96203</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1700a7fc-a422-4500-8b94-a8bebf468102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba455b82-045b-4031-b997-4bebe50a2281</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45419c62-64ba-47c2-bfdf-ecff26ec949c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9cf4540-97a9-4d5c-8e59-ea0fe1d5b06e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94e0e500-e769-475c-bb80-f4c2fa075d59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Inventory Module/Warehouse Transfers/verify_Warehouse Transfers In</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50308daf-5b42-40ce-9250-e39913476807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e5295a9-7509-48f8-af80-47ce7a0423ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c62fb8b-5844-4acf-a41e-67934e608fa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>683ed9ce-7732-4bb1-99ae-741c8711cbbd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
